### ISSUE TITLE
计算价格兼容问题

### ISSUE THREAD

**Issue by jeji** [rainx/pytdx#1]
def _cal_price1000(self, base_p, diff):
        return (base_p + diff)/1000
在2.7中为非真除，小数点后会被丢掉
建议1：
 def _cal_price1000(self, base_p, diff):
        return (float)(base_p + diff)/1000
建议2：
from __future__ import division

**Comment by uofarc** [comment]
return (base_p + diff)/1000.0      就可以了。

**Comment by rainx** [comment]
@jeji @uofarc 已经修复.. 感谢
