### ISSUE TITLE
多线程/多服务器/轮换查询的办法

### ISSUE THREAD

**Issue by yutiansut** [rainx/pytdx#101]
关于如何建立稳定的实盘查询连接:

1. 有一个服务器筛选器线程 不阻塞当前主线程
2. 有一个连接池的Queue  当某一个服务器出错的时候 替换用另外一个连接进行获取,同时把坏服务器ip剔除出这个queue

参考代码:

https://github.com/yutiansut/QUANTAXIS/blob/master/QUANTAXIS/QAFetch/QATdx_adv.py

**Comment by rainx** [comment]
cool

**Comment by rainx** [comment]
后续有时间我也整合到pytdx里面..
