### ISSUE TITLE
解析本地的历史分笔交易文件

### ISSUE THREAD

**Issue by ghost** [rainx/pytdx#103]
在本地文件目录下有个tick文件，是历史分笔交易文件，包括索引文件.idx和数据文件.ntc，能否提供读取这类文件的功能？

**Comment by yutiansut** [comment]
试过 感觉没啥意义 信息太少了

**Comment by yutiansut** [comment]
idx里面是日期和股票  ntc里面的数据基本和服务器一致

**Comment by linbingduan** [comment]
基本破解不了。idx破解了一部分。ntc只破解到每天的数据块大小，内部数据就不知道了。留个联系方式交流一下？@yutiansut

**Comment by yssource** [comment]
`vipdoc/datetick/20171222.tic` 通达信的日线数据和5分钟数据都是从这个 *.tic 文件 转档 过来的.  能 解读这个*.tic 文件的话, 其它任何时间的 比如 20151222.tic 等等, 历史数据就容易拿到

**Comment by yutiansut** [comment]
tic其实就是历史的transaction数据呀 ...

**Comment by yssource** [comment]
是的. 我是说, 本地解析 这 .tic 文件, 意义是不一样的. @https://github.com/yutiansut/QUANTAXIS/issues/397

**Comment by yutiansut** [comment]
正在考虑公共服务器维护一部分列数据的tick

**Comment by datochan** [comment]
@ghost @yssource  @yutiansut 

tic文件是以日期整理的分笔数据，ntc&etc文件是以某只股票或者基金债券组织的分笔数据，数据内容和结构上基本一致。

只不过ntc&etc文件存储数据需要考虑某个日期数据缺失的问题，所以特意配上了一个idx或者edx这类的索引文件来方便ntc和etc文件的解析而已。

所以，这个话题直接一起合并到 #149 这里一起讨论吧。
