### ISSUE TITLE
想确定一下,所得到的数据是否有复权?

### ISSUE THREAD

**Issue by smallevil** [rainx/pytdx#104]
用这个得到的数据,是否有复权??如果有,是前复权还是后复权??
是不管得到日K,周K,分钟K都有复权?还是怎么样的??
翻了半天,也没找到针对这个的说明.

有明白的回一下呗.
特别是实时行情,是否复权的?

**Comment by yutiansut** [comment]
复权要自己算

**Comment by smallevil** [comment]
也就是得到的所有数据都是未复权的??
这个怎么算??
有没有相关代码?
谢谢

**Comment by yutiansut** [comment]
我写了个在quantaxis里面

**Comment by smallevil** [comment]
好的.多谢
我找找去

**Comment by lhzw** [comment]
@yutiansut 借宝地请教个问题，我试了下那个获取除权信息的函数，600300好像是从2000开始的，000651好像是1996年开始的，可以指定起始日期么？还是怎么样的？看了下函数，没有日期参数。issue从后看过来，暂时还没有看到相关问题。

**Comment by lhzw** [comment]
的确如此，汗，感谢。
