### ISSUE TITLE
你好，是否可以支持LEVEL2的获取？

### ISSUE THREAD

**Issue by zjqzero** [rainx/pytdx#106]
感谢有这么好的工具分享，请教一下是否有计划支持LEVEL2呢

**Comment by yutiansut** [comment]
暂时不支持

**Comment by exports** [comment]
对于level2的支持可以提供下思路吗

**Comment by rainx** [comment]
因为没有level2 的账号，所以没有研究 @exports 思路主要是抓包和反向工程通达信或者网上现有的实现的dll

**Comment by yutiansut** [comment]
@rainx 之前有个issue提过tdx安卓客户端的反编译源代码

**Comment by dofish** [comment]
> 因为没有level2 的账号，所以没有研究 @exports 思路主要是抓包和反向工程通达信或者网上现有的实现的dll

大佬，我愿意提供给你level2账户供你研究：）

**Comment by yutiansut** [comment]
l2是加密的数据 可以直接用tradex 获取 


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: dofish <notifications@github.com>
发送时间: 2019年7月11日 18:34
收件人: rainx/pytdx <pytdx@noreply.github.com>
抄送: Vincent yu <yutiansut@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[rainx/pytdx] 你好，是否可以支持LEVEL2的获取？ (#106)



 
因为没有level2 的账号，所以没有研究 @exports 思路主要是抓包和反向工程通达信或者网上现有的实现的dll
  
大佬，我愿意提供给你level2账户供你研究：）

**Comment by dofish** [comment]
> l2是加密的数据 可以直接用tradex 获取 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: dofish <notifications@github.com> 发送时间: 2019年7月11日 18:34 收件人: rainx/pytdx <pytdx@noreply.github.com> 抄送: Vincent yu <yutiansut@qq.com>, Comment <comment@noreply.github.com> 主题: 回复：[rainx/pytdx] 你好，是否可以支持LEVEL2的获取？ (#106) 因为没有level2 的账号，所以没有研究 @exports 思路主要是抓包和反向工程通达信或者网上现有的实现的dll 大佬，我愿意提供给你level2账户供你研究：） — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

百度一圈，只看到tradeX.dll 这个 和 码主说的“目前采用调用网上常见的trade.dll的方式实现，trade.dll并不是我开发的” 是一样的吗？
兄弟关于tradeX 有没有官网?活着GITHUB 给点指示，我这边是linux平台环境
