### ISSUE TITLE
get_security_bars查不到退市股票的历史K线

### ISSUE THREAD

**Issue by yefangok** [rainx/pytdx#107]
In [21]: api.get_security_bars(9,1, '600087', 4, 3)       #长油(退市)
Out[21]: []

In [22]: api.get_security_bars(9,0, '000033', 4, 3)      #新都退
Out[22]: []

缺少这些数据对回测不利，会产生幸存者偏差。

**Comment by yutiansut** [comment]
退市了确实查不到  但是一般来说不会出现幸存者偏差  毕竟退市公告 以及退市机制都是长期的且公开透明的过程 具有足够长的反应时间

**Comment by pyusr** [comment]
退市查来有什么用呢,呵呵,抬杠的不算
