### ISSUE TITLE
可以提供一个接口, 返回通达信服务器列表吗

### ISSUE THREAD

**Issue by iorilu** [rainx/pytdx#114]
这样可以随机一个服务器连接, 防止被ban吧

或者哪里可以获取这个列表, 自己抓下

**Comment by yutiansut** [comment]
https://github.com/yutiansut/QUANTAXIS/blob/master/QUANTAXIS/QAFetch/QATdx_adv.py

**Comment by iorilu** [comment]
哦, 我看文档有hq_hosts, 应该可以用下,希望不要经常变吧

**Comment by iorilu** [comment]
@yutiansut 看你那里写了不少扩展代码, 好东西啊
