### ISSUE TITLE
我看tushare里面现在的bar接口就是用的pytdx

### ISSUE THREAD

**Issue by iorilu** [rainx/pytdx#116]
是你们协商好的嘛? 

以后升级是否同步...

应该直接用tushare还是用pytdx呢

**Comment by yutiansut** [comment]
tushare的版本稍微落后了一点 两者之间不兼容

**Comment by rainx** [comment]
原则上我是不太希望jimmy用这样的方式整合pytdx的，会造成软件包版本安装的冲突，但是现在还没有特别好的解决方式，如果主要使用tdx模块相关功能，还是使用pytdx吧..
