### ISSUE TITLE
能否提供一个返回一个区间交易日的接口

### ISSUE THREAD

**Issue by iorilu** [rainx/pytdx#117]
就是给start_date, end_date
返回一个交易日list

以上是大盘的
如果能获取某个股票交易日就更好

**Comment by leegb** [comment]
这个自己这就OK啦，不难啊

**Comment by yutiansut** [comment]
已经实现了啊

**Comment by iorilu** [comment]
@yutiansut 接口在哪里呢, 文档里好像没看到

**Comment by JaysonAlbert** [comment]
https://github.com/rainx/cn_stock_holidays 这里

**Comment by yutiansut** [comment]
@iorilu 简单粗暴一点的话 https://github.com/yutiansut/QUANTAXIS/blob/master/QUANTAXIS/QAUtil/QADate_trade.py

**Comment by rainx** [comment]
嵌入到自己的程序里的话，推荐 @iorilu 可以保持更新哦
