### ISSUE TITLE
【记录】pytdx 连接到服务器后好像过一段时间后就会自动断开连接，有没有api可以检测连接状态呀？

### ISSUE THREAD

**Issue by rainx** [rainx/pytdx#12]
一贱你就笑  09:52:25
pytdx 连接到服务器后好像过一段时间后就会自动断开连接，有没有api可以检测连接状态呀？
产品研发-徐景RainX  10:16:56
连接这个阶段有没有持续有api请求？
产品研发-徐景RainX  10:17:34
这个我后面研究一下，争取可以做一个断线重连的方案... 
一贱你就笑  10:21:14
没有持续api请求，就是过一阵再请求就发现disconnect，恩，或者提供一个连接状态查询也蛮好的[表情]
产品研发-徐景RainX  10:26:07
嗯，好，暂时来说，可以考虑如果长期没有连接的话，发送一个查询市场股票数量这样的小一些的请求来维持一下
产品研发-徐景RainX  10:26:24
我后面看一下，把请求状态加一下

**Comment by yutiansut** [comment]
生产者消费者模式呀 我之前那个自动寻优的ip就是这个方式

**Comment by rainx** [comment]
@yutiansut 嗯，之前没虑太多这方面，主要是之前一只想把库的功能限定在简单的接口查询上，没想增加再多外围的东西..

**Comment by rainx** [comment]
@yutiansut 准备后续在这个api基础上，再建一个项目，提供一些数据同步服务，这个时候可以把你的这个机制加上.. .

**Comment by yutiansut** [comment]
@rainx  恩恩 类似一个状态维护的东西

**Comment by bopo** [comment]
牛掰，支持下
