### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by leegb** [rainx/pytdx#131]
get_security_bars.py模块中提到：#### 为了避免python处理浮点数的时候，浮点数运算不精确问题，这里引入了多余的代码。
如果不考虑浮点数运算问题，如何解析？望rainx大神不吝赐教。是不是每一天的数据bytes数都是不固定的？

**Comment by rainx** [comment]
哦，刚看到 @leegb 

```python
In [4]: 0.1+0.2
Out[4]: 0.30000000000000004

In [5]: (1+2)/10
Out[5]: 0.3
```
看上面的代码，大概就是这个意思
