### ISSUE TITLE
获取的股指（例如：上证50，中证500，沪深300）的tick以及分钟级别的成交量是成交金额

### ISSUE THREAD

**Issue by BruceDai003** [rainx/pytdx#132]
目的：获取上述三个股指的每天收盘前3分钟时点的累计成交量，和OHLC。
问题：尝试了ts.bar( ) 和 ts.tick( )， 其实就是调用的pytdx里面的 get_history_transaction_data( )和其他函数。

比如：t1 = ts.bar('000016', cons, start_date='2017-09-01', freq='1min', asset='INDEX')
或者tick的数据
t1 = ts.tick('000016', cons, date = '2018-01-10', asset='INDEX')
t1.set_index('datetime', inplace=True)
t1.index = pd.to_datetime(t1.index)

获取到的数据的vol一列全部都不是成交量，而是股指的成交金额，我对比了文华的。
但是个股的数据，vol一列确实是成交量。

比如这个：
![image](https://user-images.githubusercontent.com/14111577/34856226-eada669c-f77e-11e7-9be5-d348d401858a.png)
vol这一列的总和9:54的时候的数值101,777,153。明显是对应的成交额，不是成交量。
这是我晚了不到1分钟截图的文华的上证50的当天截至到9:55的图：
![image](https://user-images.githubusercontent.com/14111577/34856209-cca43414-f77e-11e7-8200-d5561c789247.png)

另外前面用ts.bar()获取的1min的数据，返回的DataFrame的成交金额amount那一列的数据也不对，是数值非常非常小的异常的数值，请看图：
![image](https://user-images.githubusercontent.com/14111577/34856094-3855bbc0-f77e-11e7-8bed-70693d2b0bef.png)

**Comment by yutiansut** [comment]
指数这块确实是这样 因为没法统计量
