### ISSUE TITLE
get_k_data在停牌时返回错误数据

### ISSUE THREAD

**Issue by ghost** [rainx/pytdx#134]
如000695价格数据，起始和结束日志分别是2018-01-12和2018-01-12，按理说停牌不应该返回数据或者应该返回特殊数据，而目前返回了错误的看起来像是有意义的数据：2018-01-12  11.73  11.73  11.73  11.73  5.877472e-39  5.877472e-39

**Comment by linbingduan** [comment]
非停牌股票也偶尔会返回错误数据，如000697。

**Comment by yutiansut** [comment]
这个没问题 你要在拿到数据以后 做一个筛选就行了 就是成交量>0

**Comment by yutiansut** [comment]
这个是部分服务器出错导致的

**Comment by yutiansut** [comment]
我是把这种数据都存起来了 然后取数据的时候做处理 
参见

[https://github.com/QUANTAXIS/QUANTAXIS/blob/master/QUANTAXIS/QAFetch/QAQuery_Advance.py#L72](https://github.com/QUANTAXIS/QUANTAXIS/blob/master/QUANTAXIS/QAFetch/QAQuery_Advance.py#L72)

**Comment by linbingduan** [comment]
跟调用时间有关吗？我15:05分后调用，不少数据是错的。比如
002631 | 2018-01-12 | 8.36 | 8.44 | 8.31 | 8.28 | 76417 | 63840412
成交量大于0，但是四个价格都是错的

**Comment by yutiansut** [comment]
......

**Comment by rainx** [comment]
> 跟调用时间有关吗？我15:05分后调用，不少数据是错的。比如
> 002631 | 2018-01-12 | 8.36 | 8.44 | 8.31 | 8.28 | 76417 | 63840412
> 成交量大于0，但是四个价格都是错的

我记得15:00多一点收盘的时候有一段时间就是会返回错误数据...最好避开这段时间
