### ISSUE TITLE
关于获取通达信Android App的行情数据， 大家集思广益，有兴趣的可以看看。

### ISSUE THREAD

**Issue by githubcyc** [rainx/pytdx#139]
目前，已将App反编译，基本了解其数据加载模式，但是其核心通信代码写在了.so文件中(相当于windows平台的.dll文件)，通过IDA pro 反汇编可以得到汇编代码/C代码，由于不懂ARM汇编，加上.so文件有大量的通信请求Api封装函数，一直没有进展。
    有兴趣的朋友可以在下方留言，我将把反编译的app 和 工具在下方留下baiduyun分享地址。

**Comment by tlhbjfunny** [comment]
要一份。谢谢！

**Comment by githubcyc** [comment]
下载链接：https://pan.baidu.com/s/1i6Tx9VB 密码：8a8y

**Comment by jscrapy** [comment]
还有个办法，不用看懂so文件，把安卓的so拿到linux上来调用，把so当成一个黑盒子。
https://github.com/unicorn-engine/unicorn 这个东西是可以在x86下模拟执行so
https://stackoverflow.com/questions/13724025/how-to-invoke-android-dynamic-library-so-in-a-x86-linux

**Comment by yutiansut** [comment]
大佬给力嗷



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: golden-cold <notifications@github.com&gt;
发送时间: 2019年11月6日 20:40
收件人: rainx/pytdx <pytdx@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[rainx/pytdx] 关于获取通达信Android App的行情数据， 大家集思广益，有兴趣的可以看看。 (#139)




还有个办法，不用看懂so文件，把安卓的so拿到linux上来调用，把so当成一个黑盒子。
 https://github.com/unicorn-engine/unicorn 这个东西是可以在x86下模拟执行so
 https://stackoverflow.com/questions/13724025/how-to-invoke-android-dynamic-library-so-in-a-x86-linux
