### ISSUE TITLE
可以扩展交易接口吗？

### ISSUE THREAD

**Issue by zhuce30hao** [rainx/pytdx#14]
既然可以读行情，应该也可以用于交易吧？

**Comment by ifdandy** [comment]
行情和交易是不同服务器

**Comment by yutiansut** [comment]
行情服务器不需要账户密码的  也没有加密

**Comment by rainx** [comment]
@zhuce30hao 开放交易接口有点难度... 不仅是技术实现上要难一些  ^_^

**Comment by yutiansut** [comment]
@zhuce30hao 还有大大要冒着被请去喝茶的风险...

**Comment by ifdandy** [comment]
@rainx 可否研究下level2行情服务器协议

**Comment by zhuce30hao** [comment]
可否告知难在哪里？ @rainx
