### ISSUE TITLE
股票涨速字段解析有错，请参考fix

### ISSUE THREAD

**Issue by a19284** [rainx/pytdx#146]
index 09b4cc0..337d01a 100644
--- a/pytdx/parser/get_security_quotes.py
+++ b/pytdx/parser/get_security_quotes.py
@@ -121,7 +121,7 @@ class GetSecurityQuotesCmd(BaseParser):
             reversed_bytes6, pos = get_price(body_buf, pos)
             reversed_bytes7, pos = get_price(body_buf, pos)
             reversed_bytes8, pos = get_price(body_buf, pos)
-            (reversed_bytes9, active2) = struct.unpack("<HH", body_buf[pos: pos + 4])
+            (reversed_bytes9, active2) = struct.unpack("<hH", body_buf[pos: pos + 4])
             pos += 4

             one_stock = OrderedDict([
@@ -167,7 +167,7 @@ class GetSecurityQuotesCmd(BaseParser):
                 ("reversed_bytes6", reversed_bytes6),
                 ("reversed_bytes7", reversed_bytes7),
                 ("reversed_bytes8", reversed_bytes8),
-                ("reversed_bytes9", reversed_bytes9),
+                ("reversed_bytes9", reversed_bytes9/100),
                 ("active2", active2)
             ])
             stocks.append(one_stock)

**Comment by rainx** [comment]
收到，我处理一下

**Comment by rainx** [comment]
已修复，为了 兼容 2.x reversed_bytes9/100 变为 reversed_bytes9/100.0
