### ISSUE TITLE
lc1数据解析的不对

### ISSUE THREAD

**Issue by zzeric** [rainx/pytdx#147]
sz\minline\sz000001.lc1
                            open         high          low        close  amount   volume
2017-10-30 09:31:00  10942414.85  10942624.56  10942205.13  10942414.85  41564388.0  3600900

估计lc5也会有一样的问题

**Comment by zzeric** [comment]
版本是最新的1.63

**Comment by zzeric** [comment]
unpack的格式错了
HHIIIIfII应改为hhfffffii，然后ohlc的值不用除以100

**Comment by yutiansut** [comment]
@rainx

**Comment by rainx** [comment]
OK，收到，我看一下

**Comment by rainx** [comment]
@zzeric 有一个专门的lc_min_bar_reader.py ,不知道你是不是用的daily_bar_reader.py 而不是这个？ 这两个是分开的，两种不同的格式

**Comment by zzeric** [comment]
sorry，文档没看清楚，用了TdxMinBarReader
