### ISSUE TITLE
无法获取level1行情

### ISSUE THREAD

**Issue by ifdandy** [rainx/pytdx#15]
感谢提供该项目，相当好。只是我在下载试用的时候，发现无法获取到5档行情，我对tdx协议不了解，无法解决，请帮忙

**Comment by rainx** [comment]
@ifdandy 请问是用的是哪个服务器，获取的那只股票？ 默认的a股市场的股票应该是可以取五档行情的

--------------------
请输入要使用的功能: 1
你选择的是功能 1 : 获取股票行情
--------------------
参数：市场代码， 股票代码， 如： 0,000001 或 1,600300
请输入参数  [0,000001]:
--------------------
   market    code  active1  price  last_close   open   high    low  \
0       0  000001     1805  10.76       10.59  10.61  10.81  10.58

       reversed_bytes0  reversed_bytes1   ...      ask5  bid_vol5  ask_vol5  \
0  [128, 194, 198, 10]            -1076   ...     10.81      2088      2168

   reversed_bytes4  reversed_bytes5  reversed_bytes6  reversed_bytes7  \
0          (3001,)                1              -58              -37

   reversed_bytes8  reversed_bytes9  active2
0               -3            65509     1805

**Comment by ifdandy** [comment]
@rainx 代码如下：
with api.connect('202.102.90.146', 7709):
    #data = api.get_transaction_data(TDXParams.MARKET_SH, '600122', 0, 30)
    data = api.get_security_quotes([(TDXParams.MARKET_SH, "600122")])
    print(data)
返回是None。我换了好几个服务器都返回None，包括代码里提供的几个，比如'101.227.73.20'

**Comment by rainx** [comment]
```python
In [1]: from pytdx.hq import TdxHq_API
In [2]: api = TdxHq_API()
In [3]: api.connect('202.102.90.146', 7709)
In [5]: from pytdx.hq import TDXParams
In [6]: data = api.get_security_quotes([(TDXParams.MARKET_SH, "600122")])
In [7]: print(data)
[OrderedDict([('market', 1), ('code', '600122'), ('active1', 1074), ('price', 10.68), ('last_close', 10.54), ('open', 10.58), ('high', 10.76), ('low', 10.47), ('reversed_bytes0', bytearray(b'\xa0\xa6\xe3\n')), ('reversed_bytes1', -1068), ('vol', 80853), ('cur_vol', 12), ('amount', 86131440.0), ('s_vol', 36036), ('b_vol', 44817), ('reversed_bytes2', 0), ('reversed_bytes3', 0), ('bid1', 10.67), ('ask1', 10.68), ('bid_vol1', 94), ('ask_vol1', 171), ('bid2', 10.66), ('ask2', 10.69), ('bid_vol2', 760), ('ask_vol2', 345), ('bid3', 10.65), ('ask3', 10.7), ('bid_vol3', 1282), ('ask_vol3', 2042), ('bid4', 10.64), ('ask4', 10.71), ('bid_vol4', 154), ('ask_vol4', 421), ('bid5', 10.63), ('ask5', 10.72), ('bid_vol5', 185), ('ask_vol5', 153), ('reversed_bytes4', (8,)), ('reversed_bytes5', 1), ('reversed_bytes6', -25), ('reversed_bytes7', -31), ('reversed_bytes8', -7), ('reversed_bytes9', 0), ('active2', 1074)])]
```

我测试了一下，这里是可以的，请问你的api使用的是TdxHq_API 这个类么？ 如果尝试还是有问题的话，可以尝试升级一下pytdx试试

**Comment by ifdandy** [comment]
@rainx 我是昨天从git拉的代码，环境是win7-64bit. Python2.7-64bit。目前返回还是None，获取不到行情

**Comment by rainx** [comment]
好的，我试试windows,之前开发一支是在macos 下的，可能会有写不兼容的问题

**Comment by rainx** [comment]
@ifdandy 在win7下的py2.7和3.6都试了一下，好像还是可以的，不知道是不是因为我的系统是32位的差别，另外，你的依赖包安装了么？ 如果不行的话，可以用 pip -U install pytdx 安装一下pypi的版本试试，不确定 github上面会不会有某个时刻的版本是有问题的

**Comment by ifdandy** [comment]
@rainx 另外我在centos-6.6-Final，64bit，Python 2.7.5，获取的也是None。

Centos上的版本我是刚从git下载的。
api = TdxHq_API()
    if api.connect('101.227.73.20', 7709):
        log.info("获取股票行情")
        stocks = api.get_security_quotes([(1, "600122")])
        pprint.pprint(stocks)
        exit()

Print：
2017-07-28 15:36:16,427 - PYTDX - INFO - 获取股票行情
2017-07-28 15:36:16,427 - PYTDX - INFO - 获取股票行情
None

**Comment by rainx** [comment]
@ifdandy 可以试试 hqget 命令行程序，是不是也无法获取数据？ 我刚才试了一下ubuntu下的 python2.7.12是可以的

**Comment by ifdandy** [comment]
@rainx 有qq群之类的交流吗？我这边始终无法获取到数据

**Comment by rainx** [comment]
QQ群：4993284
