### ISSUE TITLE
是否能获得道琼斯指数历史数据呢？

### ISSUE THREAD

**Issue by xyooyy** [rainx/pytdx#151]
找了半天没找到指数的代码 不知道能不能获得美股主要指数的日k线数据

**Comment by rainx** [comment]
不同的服务器返回的结果不太一样，你可以试试 https://rainx.gitbooks.io/pytdx/content/pytdx_exhq.html 里面 api.get_markets() 看看， 我看到有的服务器有 
```
15      37        11    国际指数         FW
```
然后再进行查找，
可能有的服务器有
