### ISSUE TITLE
历史专业财务数据里有重复的记录

### ISSUE THREAD

**Issue by lte2000** [rainx/pytdx#152]
比如gpcw20170331.zip, 调用HistoryFinancialCrawler() parse() 和 to_df()以后, 得到的数据里有四个股票含2条记录, 它们是:
code, report_date
(u'000063', 20170331L)
(u'300635', 20170331L)
(u'300636', 20170331L)
(u'601200', 20170331L)
不知道是源文件里就是这样的, 还是解析出错了?

**Comment by rainx** [comment]
这个不太确定，根据代码还不太能确定问题，我猜测可能还是提供数据的文件的问题吧
