### ISSUE TITLE
 api.get_security_count(0), api.get_security_list(1,100) 为什么都返回None ？

### ISSUE THREAD

**Issue by laowalter** [rainx/pytdx#157]
`
Python 3.6.3 (default, Jan  7 2018, 22:22:02)
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytdx.hq import TdxHq_API
>>> api = TdxHq_API()
>>> num = api.get_security_count(0)
>>> print(num)
None
>>>
`

**Comment by rainx** [comment]
需要api.connect  在进行后续步骤
