### ISSUE TITLE
get_history_transaction_data() get 510050 eft return wrong data

### ISSUE THREAD

**Issue by WalterCK** [rainx/pytdx#159]
params = ['1', '510050', '0', '100', '20180329']
        d = get_history_transaction_data(params)

**Comment by rainx** [comment]
输入的参数是错误的， get_history_transaction_data 不是使用数组作为参数.. 并且有些字段是数字类型，不是字符串

**Comment by WalterCK** [comment]
from pytdx.hq import TdxHq_API
c = api.connect('61.135.142.88', 7709)
params = ['1', '510050', '0', '100', '20180329']
data = api.get_transaction_data(int(params[0]), params[1], int(params[2]), int(params[3]))

return wrong data

**Comment by yutiansut** [comment]
价格/10即可

**Comment by WalterCK** [comment]
Hi Vincent,


Thanks for your reply. It seems price/10 can match real data. Thanks for your time again.


Thanks,

Walter


________________________________
发件人: Vincent yu <notifications@github.com>
发送时间: 2018年5月12日 17:35
收件人: rainx/pytdx
抄送: WalterCK; Author
主题: Re: [rainx/pytdx] get_history_transaction_data() get 510050 eft return wrong data (#159)


价格/10即可

―
