### ISSUE TITLE
510050 get_history_transaction_data return wrong data

### ISSUE THREAD

**Issue by WalterCK** [rainx/pytdx#161]
from pytdx.hq import TdxHq_API
c = api.connect('61.135.142.88', 7709)
params = ['1', '510050', '0', '100', '20180329']
data = api.api.get_history_transaction_data(int(params[0]), params[1], int(params[2]), int(params[3]), int(params[4]))

return wrong data

**Comment by WalterCK** [comment]
Vincent yu <notifications@github.com>
价格/10即可

非常感谢Vincent 帮确认了一下etf价格的换算方法.

**Comment by yutiansut** [comment]
ha  这里的本质原因是  通达信给的浮点数不一致的问题 这个/10的办法是最简单的
