### ISSUE TITLE
财务指标英文更新

### ISSUE THREAD

**Issue by yutiansut** [rainx/pytdx#163]
在@rainx大大和@datoChen的努力下,财务指标的获取成为了现实,但是目前财务没有一个英文的解释,我对照tdx和财务英语,用驼峰的形式补齐了所有的英文解释

https://github.com/QUANTAXIS/QUANTAXIS/blob/master/QUANTAXIS/QAData/financial_mean.py

目前还在校对中

**Comment by yutiansut** [comment]
@rainx

**Comment by rainx** [comment]
cool 已经更新到文档中..  https://rainx.gitbooks.io/pytdx/content/pytdx_crawler.html
