### ISSUE TITLE
关于send_order接口

### ISSUE THREAD

**Issue by kadeemding** [rainx/pytdx#164]
api.send_order(client_id, category, price_type, gddm, zqdm, price, quantity)

category
price_type
gddm
zddm
这4个参数分别指什么？

**Comment by rainx** [comment]
可以参考 trade.dll  对应的文档

https://wenku.baidu.com/view/1b57c3b4a26925c52dc5bfb4.html

/// &lt;param name="Category"&gt;表示委托的种类，0买入 1卖出  2融资买入  3融券卖出   4买券还券   5卖券还款  6现券还券&lt;/param&gt;

/// &lt;param name="PriceType"&gt;表示报价方式 0上海限价委托 深圳限价委托 1(市价委托)深圳对方最优价格  2(市价委托)深圳本方最优价格  3(市价委托)深圳即时成交剩余撤销  4(市价委托)上海五档即成剩撤 深圳五档即成剩撤 5(市价委托)深圳全额成交或撤销 6(市价委托)上海五档即成转限价

**Comment by kadeemding** [comment]
了解。谢谢。
