### ISSUE TITLE
期货数据里面的 amount 数据不对

### ISSUE THREAD

**Issue by hardywu** [rainx/pytdx#165]
amount 数据的量级不可能是e-41

![yloxap32atyj 085fgqjcad](https://user-images.githubusercontent.com/954064/41318888-826c475e-6ecc-11e8-83ca-97efbb7f9c8a.png)

**Comment by yutiansut** [comment]
期货里面没有amount字段....这不是bug

**Comment by yutiansut** [comment]
因为扩展行情里面 有期货有港股, 期货没有amount字段 港股有  所以期货部分之间忽略就行

**Comment by hardywu** [comment]
我去，原来 tdx 本来就没有交易额数据
