### ISSUE TITLE
api.get_transaction_data为什么取出来的成交明细不完整？？

### ISSUE THREAD

**Issue by gooongooon** [rainx/pytdx#166]
小白刚开始学习，提个问题：

为何调用这个api有时候取出来的数据是不完整的？？下面同一天提取的全部成交明细，一个是从9：25开始提取的，一个数据却不完整只有从10：56开始的数据。谢谢！！

![11](https://user-images.githubusercontent.com/40315604/41507542-bf9c7d90-7266-11e8-9155-f28428c2a8fc.jpg)
![12](https://user-images.githubusercontent.com/40315604/41507543-c1fee226-7266-11e8-94a0-c4978358af41.jpg)

**Comment by yutiansut** [comment]
因为你请求的数据不完整 参见 https://github.com/QUANTAXIS/QUANTAXIS/blob/master/QUANTAXIS/QAFetch/QATdx.py#L690

**Comment by gooongooon** [comment]
@yutiansut 多谢！

**Comment by neilyoung2008** [comment]
为什么运行项目里面的hq.py，显示num都为0 ？
`[OrderedDict([('time', '14:58'),
              ('price', 10.04),
              ('vol', 16),
              ('num', 0),
              ('buyorsell', 1)]),
 OrderedDict([('time', '14:58'),
              ('price', 10.04),
              ('vol', 42),
              ('num', 0),
              ('buyorsell', 1)]),
 OrderedDict([('time', '14:58'),
              ('price', 10.04),
              ('vol', 12),
              ('num', 0),
              ('buyorsell', 1)]),
 OrderedDict([('time', '14:58'),
              ('price', 10.05),
              ('vol', 28),
              ('num', 0),
              ('buyorsell', 0)]),
 OrderedDict([('time', '14:58'),
              ('price', 10.04),
              ('vol', 26),
              ('num', 0),
              ('buyorsell', 1)]),
 OrderedDict([('time', '14:58'),
              ('price', 10.04),
              ('vol', 2),
              ('num', 0),
              ('buyorsell', 1)]),
 OrderedDict([('time', '14:58'),
              ('price', 10.05),
              ('vol', 158),
              ('num', 0),
              ('buyorsell', 0)]),
 OrderedDict([('time', '14:58'),
              ('price', 10.04),
              ('vol', 5),
              ('num', 0),
              ('buyorsell', 1)]),
 OrderedDict([('time', '14:58'),
              ('price', 10.05),
              ('vol', 59),
              ('num', 0),
              ('buyorsell', 0)]),
 OrderedDict([('time', '14:58'),
              ('price', 10.04),
              ('vol', 1),
              ('num', 0),
              ('buyorsell', 1)]),
 OrderedDict([('time', '14:58'),
              ('price', 10.04),
              ('vol', 120),
              ('num', 0),
              ('buyorsell', 1)]),
 OrderedDict([('time', '14:58'),
              ('price', 10.05),`

**Comment by yutiansut** [comment]
那个是方向
