### ISSUE TITLE
求助码主：get_time(buffer, pos)

### ISSUE THREAD

**Issue by gooongooon** [rainx/pytdx#168]
实际调用get_transaction_data()的时候发现返回的tick数据里面，时间字段只有小时+分钟，但分析吃单的算法里面对于秒数也有一定的需求（就是3秒一个，不超过20个）。
自己对这个数据结构不了解也无法，不知道码主修改这里的代码是否可行？如果不影响整体代码的话，建议这里增加到秒的级别。

后来看到源代码是这个地方：

helper里面这个get_time(buffer, pos)，当前只能返回hour & minute，是否可能增加到hour+mintue+second? 求助大神 @rainx @yutiansut 
*********************************************************
def get_time(buffer, pos):         
    (tminutes, ) = struct.unpack("<H", buffer[pos: pos + 2])
    hour = int(tminutes / 60)
    minute = tminutes % 60
    pos += 2

    return hour, minute, pos
**********************************************************

**Comment by yutiansut** [comment]
不行的 因为通达信自己就没有秒  软件上可以看到 

基本上4800条就是3秒一条

**Comment by gooongooon** [comment]
主要是还有一个问题，理论上一分钟最多20条，
但是如果说一分钟内，成交稀少，可能一共只有3-5条，没办法分辨具体的时间点。。。
实时分析的时候，同一分钟里推送进来的数据，没办法分辨出是否一条新增的tick。

如果我写一个函数3秒读取一次获取（start=0, count=1）数据，但看不出来这条是和之前一条重复，还是说新增的但是其他数据一样。

**Comment by rainx** [comment]
貌似有一个字段有序列信息，不太确定，有点忘记了
