### ISSUE TITLE
pytdx 获取分钟数据出入太大

### ISSUE THREAD

**Issue by mdhhdm** [rainx/pytdx#169]
![image](https://user-images.githubusercontent.com/7555815/42698291-0b090846-86f0-11e8-958e-b1ff36259048.png)

实际通达信软件 7月11号的数据 收盘价是7元上波动 ，求问各位大神，这是啥原因

**Comment by testttt0** [comment]
原因是通达信软件显示的价格进行了除权处理

**Comment by yutiansut** [comment]
@mdhhdm @testttt0 这个是不复权数据，复权办法参考 https://github.com/QUANTAXIS/QUANTAXIS/blob/master/QUANTAXIS/QAData/QADataStruct.py
