### ISSUE TITLE
试图解析有高开低收的分钟线

### ISSUE THREAD

**Issue by mifox** [rainx/pytdx#17]
时间	开盘价	最高价	最低价	收盘价	持仓	成交	结算
20160804	3166.199951	3178.000000	3145.000000	3177.199951	30489	10262	3171.600098
20160805	3181.000000	3209.800049	3166.199951	3193.000000	30331	10937	3191.399902
20160808	3190.000000	3224.399902	3168.199951	3223.000000	30029	11751	3216.600098
20160809	3221.000000	3247.000000	3215.000000	3244.000000	29372	10838	3239.000000
20160810	3244.199951	3252.199951	3231.000000	3234.199951	28266	8585	3235.600098
20160811	3231.600098	3269.600098	3226.000000	3226.199951	27821	12119	3237.600098

请求格式如下
[01 01 08 6A 01 01 16 00 16 00 FF 23 4A 4E 56 44 41 00 00 00 00 13 09 00 01 00 00 00 00 00 F0 00]
感觉回复格式经过了压缩 
能否加微信讨论 mi-fox

**Comment by rainx** [comment]
@mifox 1.16版本已经添加了..
