### ISSUE TITLE
分时成交数据中的num有误 。api.get_transaction_data

### ISSUE THREAD

**Issue by neilyoung2008** [rainx/pytdx#174]
**以下引用自hq.py文件：**
```
log.info("查询分时成交")
data = api.get_transaction_data(TDXParams.MARKET_SH, '600000', 0, 30)
pprint.pprint(data)    
```
**输出里面的num全部为0， 我看之前的讨论，num的值都是>=1的啊！！！**

`[OrderedDict([('time', '14:58'), ('price', 10.04), ('vol', 16), ('num', 0), ('buyorsell', 1)]), OrderedDict([('time', '14:58'), ('price', 10.04), ('vol', 42), ('num', 0), ('buyorsell', 1)]), OrderedDict([('time', '14:58'), ('price', 10.04), ('vol', 12), ('num', 0), ('buyorsell', 1)]), OrderedDict([('time', '14:58'), ('price', 10.05), ('vol', 28), ('num', 0), ('buyorsell', 0)]), OrderedDict([('time', '14:58'), ('price', 10.04), ('vol', 26), ('num', 0), ('buyorsell', 1)]), OrderedDict([('time', '14:58'), ('price', 10.04), ('vol', 2), ('num', 0), ('buyorsell', 1)]), OrderedDict([('time', '14:58'), ('price', 10.05), ('vol', 158), ('num', 0), ('buyorsell', 0)]), OrderedDict([('time', '14:58'), ('price', 10.04), ('vol', 5), ('num', 0), ('buyorsell', 1)]), OrderedDict([('time', '14:58'), ('price', 10.05), ('vol', 59), ('num', 0), ('buyorsell', 0)]), OrderedDict([('time', '14:58'), ('price', 10.04), ('vol', 1), ('num', 0), ('buyorsell', 1)]), OrderedDict([('time', '14:58'), ('price', 10.04), ('vol', 120), ('num', 0), ('buyorsell', 1)]), OrderedDict([('time', '14:58'), ('price', 10.05),`

**Comment by tigersean** [comment]
换服务器, 服务器的没有这些信息

**Comment by yutiansut** [comment]
有不少券商缺少数据运维能力....

**Comment by neilyoung2008** [comment]
券商服务器的问题，深圳上海的实时分笔成交数据都是有num的
