### ISSUE TITLE
CONNECT_TIMEOUT应该灵活可配置

### ISSUE THREAD

**Issue by zjqzero** [rainx/pytdx#177]
现实的需求  3s一次的quote，如果等待5s超时对于高频的策略是不合适的

**Comment by yutiansut** [comment]
timeout是可以自定义的  with api.connect(ip, port, time_out=0.7)

**Comment by zjqzero** [comment]
我看了下接口，好像没有time_out参数，取的CONNECT_TIMEOUT

```
    def connect(self, ip='101.227.73.20', port=7709):
        """

        :param ip:  服务器ip 地址
        :param port:  服务器端口
        :return: 是否连接成功 True/False
        """
        self.client = TrafficStatSocket(socket.AF_INET, socket.SOCK_STREAM)
        self.client.settimeout(CONNECT_TIMEOUT)
        log.debug("connecting to server : %s on port :%d" % (ip, port))
```

**Comment by yutiansut** [comment]
def connect(self, ip='101.227.73.20', port=7709, time_out=CONNECT_TIMEOUT, bindport=None, bindip='0.0.0.0'):

**Comment by yutiansut** [comment]
这里https://github.com/rainx/pytdx/blob/master/pytdx/base_socket_client.py#L129

**Comment by zjqzero** [comment]
最新的代码是有，是否可以麻烦发布下版本，我pip install的，多谢

**Comment by yutiansut** [comment]
@zjqzero  你卸了重装下   参见这个问题 https://github.com/QUANTAXIS/QUANTAXIS/issues/747

**Comment by zjqzero** [comment]
另外请教一下，heartbeat启用后，如果断链，会自动重连吗？
我看到有个pool的功能，如果能过做到负荷分担就好了，N:M备份，1:M全部集中在一个券商那里，全市场获取比较尴尬

**Comment by yutiansut** [comment]
我写过一个分散请求的 

不建议启动心跳


https://github.com/QUANTAXIS/QUANTAXIS/blob/master/QUANTAXIS/QAFetch/QATdx_adv.py

**Comment by zjqzero** [comment]
恩，我测试下来主要是connect容易造成timeout，获取全市场盘口，每次连接制造了大部分时延；这也是TIMEOUT要可配，情愿放弃这次连接；如果连接池能保持住活动连接的话，延迟就可以进一步缩短
