### ISSUE TITLE
获取股票行情是否有字段可以显示时间点

### ISSUE THREAD

**Issue by zjqzero** [rainx/pytdx#178]
{
        'market': 0,
        'code': '000333',
        'active1': 4672,
        'price': 42.91,
        'last_close': 41.38,
        'open': 41.85,
        'high': 42.96,
        'low': 41.7,
        'reversed_bytes0': 14996010,
        'reversed_bytes1': -4291,
        'vol': 380328,
        'cur_vol': 3998,
        'amount': 1615957760.0,
        's_vol': 193478,
        'b_vol': 186850,
        'reversed_bytes2': 2,
        'reversed_bytes3': 44026,
        'bid1': 42.91,
        'ask1': 42.92,
        'bid_vol1': 618,
        'ask_vol1': 843,
        'bid2': 42.9,
        'ask2': 42.93,
        'bid_vol2': 320,
        'ask_vol2': 240,
        'bid3': 42.89,
        'ask3': 42.94,
        'bid_vol3': 277,
        'ask_vol3': 219,
        'bid4': 42.88,
        'ask4': 42.95,
        'bid_vol4': 375,
        'ask_vol4': 666,
        'bid5': 42.87,
        'ask5': 42.96,
        'bid_vol5': 26,
        'ask_vol5': 672,
        'reversed_bytes4': (842, ),
        'reversed_bytes5': 1,
        'reversed_bytes6': -186,
        'reversed_bytes7': -248,
        'reversed_bytes8': -110,
        'reversed_bytes9': 0.0,
        'active2': 4672
    }

reversed_bytes0 是不是时间戳

**Comment by yutiansut** [comment]
# reversed_bytes9 --> 涨速
    # active1,active2 --> 活跃度
    # reversed_bytes1 --> -价格*100
    # vol 总量 cur_vol 现量
    # amount 总金额
    # s_vol 内盘 b_vol 外盘
    # reversed_bytes2 市场

**Comment by yutiansut** [comment]
时间的只能用自己本地时间戳了

**Comment by zjqzero** [comment]
好的，多谢，好像是通达信没有提供时间，没有时间有些判断就变的复杂了
