### ISSUE TITLE
扩展市场1分钟数据价格有问题

### ISSUE THREAD

**Issue by yukking** [rainx/pytdx#179]
我用TdxMinBarReader读取lc1格式的扩展行情，例如恒生指数，得到的数据与真实价格差很多倍，估计是有另一条转换公式。
![image](https://user-images.githubusercontent.com/8501077/44804304-84e80180-abf3-11e8-8301-37602f5b354d.png)

**Comment by yutiansut** [comment]
list里面有倍数信息
