### ISSUE TITLE
get_minute_time_data返回不正确的数据。

### ISSUE THREAD

**Issue by jeffery82** [rainx/pytdx#184]
hq.connect('119.147.171.207', 7709)
r = hq.get_minute_time_data(1, '600603')
for i in r:
    print(i)

返回结果如下：
OrderedDict([('price', 0.01), ('vol', 48)])
OrderedDict([('price', 0.49), ('vol', 48)])
OrderedDict([('price', 1.0), ('vol', 1)])
OrderedDict([('price', 4.88), ('vol', -5)])
OrderedDict([('price', 4.88), ('vol', 14391813)])
OrderedDict([('price', 1.0), ('vol', 20)])
OrderedDict([('price', -784097.26), ('vol', 9784)])
OrderedDict([('price', -784097.26), ('vol', 0)])
OrderedDict([('price', -784097.25), ('vol', 560)])
OrderedDict([('price', -784097.26), ('vol', 364)])
OrderedDict([('price', -784089.75), ('vol', 3)])
OrderedDict([('price', -784085.36), ('vol', 969)])
OrderedDict([('price', -784081.55), ('vol', 97)])
OrderedDict([('price', -784081.54), ('vol', 93)])
OrderedDict([('price', -784081.54), ('vol', 12)])
OrderedDict([('price', -784081.57), ('vol', 429)])
OrderedDict([('price', -784081.57), ('vol', 0)])
OrderedDict([('price', -784081.56), ('vol', 18)])
OrderedDict([('price', -784081.55), ('vol', 25)])
OrderedDict([('price', -784081.54), ('vol', 7)])
OrderedDict([('price', -784081.54), ('vol', 1)])
OrderedDict([('price', -784081.54), ('vol', 10)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.55), ('vol', 101)])
OrderedDict([('price', -784081.55), ('vol', 9)])
OrderedDict([('price', -784081.55), ('vol', 0)])
OrderedDict([('price', -784081.55), ('vol', 5)])
OrderedDict([('price', -784081.54), ('vol', 10)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.55), ('vol', 1)])
OrderedDict([('price', -784081.55), ('vol', 1)])
OrderedDict([('price', -784081.55), ('vol', 104)])
OrderedDict([('price', -784081.55), ('vol', 0)])
OrderedDict([('price', -784081.56), ('vol', 26)])
OrderedDict([('price', -784081.55), ('vol', 41)])
OrderedDict([('price', -784081.55), ('vol', 0)])
OrderedDict([('price', -784081.55), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 335)])
OrderedDict([('price', -784081.53), ('vol', 1)])
OrderedDict([('price', -784081.53), ('vol', 197)])
OrderedDict([('price', -784081.53), ('vol', 96)])
OrderedDict([('price', -784081.53), ('vol', 2)])
OrderedDict([('price', -784081.53), ('vol', 0)])
OrderedDict([('price', -784081.53), ('vol', 19)])
OrderedDict([('price', -784081.53), ('vol', 134)])
OrderedDict([('price', -784081.53), ('vol', 0)])
OrderedDict([('price', -784081.53), ('vol', 43)])
OrderedDict([('price', -784081.52), ('vol', 15)])
OrderedDict([('price', -784081.52), ('vol', 54)])
OrderedDict([('price', -784081.52), ('vol', 0)])
OrderedDict([('price', -784081.52), ('vol', 12)])
OrderedDict([('price', -784081.52), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 892)])
OrderedDict([('price', -784081.54), ('vol', 112)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 213)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.53), ('vol', 50)])
OrderedDict([('price', -784081.54), ('vol', 200)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.53), ('vol', 54)])
OrderedDict([('price', -784081.53), ('vol', 20)])
OrderedDict([('price', -784081.53), ('vol', 0)])
OrderedDict([('price', -784081.53), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 67)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.56), ('vol', 1447)])
OrderedDict([('price', -784081.56), ('vol', 15)])
OrderedDict([('price', -784081.54), ('vol', 40)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.55), ('vol', 30)])
OrderedDict([('price', -784081.54), ('vol', 10)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.55), ('vol', 41)])
OrderedDict([('price', -784081.55), ('vol', 1)])
OrderedDict([('price', -784081.54), ('vol', 30)])
OrderedDict([('price', -784081.55), ('vol', 13)])
OrderedDict([('price', -784081.55), ('vol', 79)])
OrderedDict([('price', -784081.55), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 89)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 77)])
OrderedDict([('price', -784081.54), ('vol', 39)])
OrderedDict([('price', -784081.55), ('vol', 1)])
OrderedDict([('price', -784081.55), ('vol', 1063)])
OrderedDict([('price', -784081.54), ('vol', 80)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.55), ('vol', 4)])
OrderedDict([('price', -784081.55), ('vol', 0)])
OrderedDict([('price', -784081.55), ('vol', 0)])
OrderedDict([('price', -784081.55), ('vol', 0)])
OrderedDict([('price', -784081.55), ('vol', 0)])
OrderedDict([('price', -784081.55), ('vol', 4)])
OrderedDict([('price', -784081.55), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 92)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 10)])
OrderedDict([('price', -784081.54), ('vol', 71)])
OrderedDict([('price', -784081.53), ('vol', 89)])
OrderedDict([('price', -784081.53), ('vol', 0)])
OrderedDict([('price', -784081.53), ('vol', 0)])
OrderedDict([('price', -784081.53), ('vol', 0)])
OrderedDict([('price', -784081.53), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 23)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 97)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 3)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 154)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.55), ('vol', 101)])
OrderedDict([('price', -784081.55), ('vol', 255)])
OrderedDict([('price', -784081.55), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 1)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 44)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 114)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.55), ('vol', 74)])
OrderedDict([('price', -784081.54), ('vol', 59)])
OrderedDict([('price', -784081.54), ('vol', 70)])
OrderedDict([('price', -784081.54), ('vol', 51)])
OrderedDict([('price', -784081.55), ('vol', 21)])
OrderedDict([('price', -784081.54), ('vol', 11)])
OrderedDict([('price', -784081.54), ('vol', 0)])
OrderedDict([('price', -784081.51), ('vol', 1056)])
OrderedDict([('price', -784081.52), ('vol', 58)])
OrderedDict([('price', -784081.51), ('vol', 148)])
OrderedDict([('price', -784081.51), ('vol', 33)])
OrderedDict([('price', -784081.51), ('vol', 472)])
OrderedDict([('price', -784081.51), ('vol', 326)])
OrderedDict([('price', -784081.52), ('vol', 2)])
OrderedDict([('price', -784081.52), ('vol', 169)])
OrderedDict([('price', -784081.52), ('vol', 0)])
OrderedDict([('price', -784081.52), ('vol', 0)])
OrderedDict([('price', -784081.52), ('vol', 132)])
OrderedDict([('price', -784081.52), ('vol', 18)])
OrderedDict([('price', -784081.52), ('vol', 43)])
OrderedDict([('price', -784081.52), ('vol', 0)])
OrderedDict([('price', -784081.52), ('vol', 76)])
OrderedDict([('price', -784081.52), ('vol', 0)])
OrderedDict([('price', -784081.51), ('vol', 130)])
OrderedDict([('price', -784081.51), ('vol', 1)])
OrderedDict([('price', -784081.51), ('vol', 13)])
OrderedDict([('price', -784081.51), ('vol', 26)])
OrderedDict([('price', -784081.51), ('vol', 0)])
OrderedDict([('price', -784081.5), ('vol', 648)])
OrderedDict([('price', -784081.51), ('vol', 10)])
OrderedDict([('price', -784081.5), ('vol', 847)])
OrderedDict([('price', -784081.49), ('vol', 674)])
OrderedDict([('price', -784081.5), ('vol', 130)])
OrderedDict([('price', -784081.49), ('vol', 91)])
OrderedDict([('price', -784081.5), ('vol', 50)])
OrderedDict([('price', -784081.5), ('vol', 164)])
OrderedDict([('price', -784081.5), ('vol', 2)])
OrderedDict([('price', -784081.5), ('vol', 5)])
OrderedDict([('price', -784081.5), ('vol', 0)])
OrderedDict([('price', -784081.5), ('vol', 71)])
OrderedDict([('price', -784081.5), ('vol', 10)])
OrderedDict([('price', -784081.49), ('vol', 161)])
OrderedDict([('price', -784081.48), ('vol', 717)])
OrderedDict([('price', -784081.48), ('vol', 0)])
OrderedDict([('price', -784081.48), ('vol', 30)])
OrderedDict([('price', -784081.48), ('vol', 331)])
OrderedDict([('price', -784081.49), ('vol', 128)])
OrderedDict([('price', -784081.49), ('vol', 223)])
OrderedDict([('price', -784081.49), ('vol', 200)])
OrderedDict([('price', -784081.48), ('vol', 249)])
OrderedDict([('price', -784081.48), ('vol', 379)])
OrderedDict([('price', -784081.48), ('vol', 83)])
OrderedDict([('price', -784081.48), ('vol', 10)])
OrderedDict([('price', -784081.48), ('vol', 110)])
OrderedDict([('price', -784081.48), ('vol', 7)])
OrderedDict([('price', -784081.48), ('vol', 169)])
OrderedDict([('price', -784081.48), ('vol', 40)])
OrderedDict([('price', -784081.49), ('vol', 31)])
OrderedDict([('price', -784081.49), ('vol', 26)])
OrderedDict([('price', -784081.49), ('vol', 1)])
OrderedDict([('price', -784081.49), ('vol', 0)])
OrderedDict([('price', -784081.49), ('vol', 13)])
OrderedDict([('price', -784081.49), ('vol', 80)])
OrderedDict([('price', -784081.49), ('vol', 0)])
OrderedDict([('price', -784081.49), ('vol', 20)])
OrderedDict([('price', -784081.48), ('vol', 160)])
OrderedDict([('price', -784081.48), ('vol', 483)])
OrderedDict([('price', -784081.48), ('vol', 0)])
OrderedDict([('price', -784081.49), ('vol', 126)])
OrderedDict([('price', -784081.48), ('vol', 216)])
OrderedDict([('price', -784081.48), ('vol', 16)])
OrderedDict([('price', -784081.48), ('vol', 137)])
OrderedDict([('price', -784081.48), ('vol', 188)])
OrderedDict([('price', -784081.48), ('vol', 26)])
OrderedDict([('price', -784081.48), ('vol', 5)])
OrderedDict([('price', -784081.48), ('vol', 10)])
OrderedDict([('price', -784081.49), ('vol', 17)])

**Comment by yutiansut** [comment]
负数?

**Comment by azluck** [comment]
get_minute_time_data的问题一直没有修复，只能暂时用get_history_minute_time_data代替

**Comment by rainx** [comment]
```

**Comment by rainx** [comment]
目前好像是可以了
```
(env) ➜  git:(dev) hqget -s 119.147.171.207:7709
连接中.... 
连接成功！
--------------------
功能列表：
1 : 获取股票行情
2 : 获取k线
3 : 获取市场股票数量
4 : 获取股票列表
5 : 获取指数k线
6 : 查询分时行情
7 : 查询历史分时行情
8 : 查询分笔成交
9 : 查询历史分笔成交
10 : 查询公司信息目录
11 : 读取公司信息详情
12 : 读取除权除息信息
13 : 读取财务信息
14 : 退出断开连接
--------------------
请输入要使用的功能: 6
你选择的是功能 6 : 查询分时行情
--------------------
参数：市场代码， 股票代码， 如： 0,000001 或 1,600300
请输入参数  [0,000001]: 1,600603
--------------------
      price    vol
0      0.01     48
1      0.49     48
2      1.00    511
3      0.97      2
4      0.92   -511
5    286.02   6698
6    285.73  16356
7    407.27      0
8    407.26    486
9    412.84      1
10   418.37     -3
11   418.39   1064
12   418.41    508
13   418.76      1
14   418.91     -1
15   419.13      0
16   419.02     -1
17   418.72      0
18   418.60     -1
19   418.06      1
20   417.90      0
21   417.85      2
22   417.95      0
23   418.01     -1
24   418.02      0
25   418.16      1
26   418.18      0
27   418.18     -1
28   418.19      0
29   418.21      1
30   418.23     -1
31   418.25      2
32   418.47      0
33   418.61      0
34   418.64     -1
35   418.65      1
36   418.72      0
37   418.73      0
38   418.82      1
39   418.86     -1
40   419.07      0
41   419.08     -1
42   419.12      1
43   419.13     -2
44   419.15      0
45   419.12      1
46   419.12      0
47   419.12     -1
48   419.10      0
49   419.09      1
50   419.09      0
51   419.09     -1
52   419.09      0
53   419.08      1
54   419.08     -1
55   419.06      1
56   419.06      0
57   419.06     -1
58   419.06      0
59   419.06      0
60   419.05      0
61   419.05      0
62   419.05     -1
63   419.05      0
64   418.62     -1
65   418.61      1
66   418.57      1
67   418.55     -1
68   418.54      0
69   418.53      0
70   418.51      1
71   418.50     -1
72   418.50      0
73   418.47      0
74   418.47      1
75   418.47      0
76   418.47      0
77   418.47      0
78   418.46      0
79   418.46      1
80   418.46      0
81   418.47     -1
82   418.47      0
83   418.47      0
84   418.47      0
85   418.47      0
86   418.47      0
87   418.47      0
88   418.47      0
89   418.47      0
90   418.47      0
91   418.47     -1
92   418.46      1
93   418.46      0
94   418.46      0
95   418.46      0
96   418.46     -1
97   418.46      1
98   418.46      0
99   418.46      0
100  418.46      0
101  418.46      0
102  418.46     -1
103  418.46      1
104  418.46      0
105  418.46      1
106  418.53      0
107  418.53     -1
108  418.53      0
109  418.53      0
110  418.53      0
111  418.53      0
112  418.53      1
113  418.54      0
114  418.55      0
115  418.57      0
116  418.57      0
117  418.57     -1
118  418.57      0
119  418.57      0
120  418.57      0
121  418.57      1
122  418.57      0
123  418.57     -1
124  418.57      0
125  418.57      0
126  418.57      1
127  418.57      0
128  418.57     -1
129  418.57      0
130  418.57      1
131  418.57     -1
132  418.57      1
133  418.57      0
134  418.57      0
135  418.57     -1
136  418.57      0
137  418.57      1
138  418.57      0
139  418.58     -1
140  418.58      0
141  418.58      0
142  418.58      0
143  418.58      0
144  418.58      0
145  418.58      0
146  418.58      0
147  418.58      0
148  418.58      0
149  418.58      1
150  418.58      0
151  418.58      0
152  418.59      0
153  418.59      0
154  418.59     -1
155  418.59      1
156  418.59      0
157  418.59      0
158  418.59     -1
159  418.59      1
160  418.59      0
161  418.59      0
162  418.59      0
163  418.59      0
164  418.59     -1
165  418.58      0
166  418.58      0
167  418.58      0
168  418.58      0
169  418.58     -1
170  418.57      0
171  418.57      0
172  418.57      0
173  418.57      1
174  418.57      0
175  418.57     -1
176  418.57      0
177  418.57      0
178  418.57      0
179  418.57      0
180  418.57      0
181  418.57      0
182  418.55      0
183  418.55      0
184  418.54      0
185  418.54      0
186  418.54      0
187  418.54      0
188  418.54      0
189  418.54     -1
190  418.53      1
191  418.53      0
192  418.53      0
193  418.53      0
194  418.53      0
195  418.53      1
196  418.53      0
197  418.53     -1
198  418.53      1
199  418.53      1
200  418.53      0
201  418.53     -1
202  418.53      0
203  418.53      1
204  418.53     -1
205  418.53      0
206  418.53      0
207  418.53      0
208  418.53      0
209  418.53      1
210  418.54      0
211  418.55     -1
212  418.55      0
213  418.55      1
214  418.55     -1
215  418.55      0
216  418.55      1
217  418.55      0
218  418.57      0
219  418.58      0
220  418.67      2
221  418.89      2
222  419.08     -2
223  419.12      1
224  419.12      0
225  419.12     -1
226  419.15     -1
227  419.15      0
228  419.16      1
229  419.16      0
230  419.16      0
231  419.16     -1
232  419.16      0
233  419.18      0
234  419.19     -1
235  419.20      1
236  419.20      0
237  419.21      0
238  419.21      0
239  419.21      0
--------------------
按任意键继续
```
