### ISSUE TITLE
Bug：  api.get_security_bars 周K线数据不对

### ISSUE THREAD

**Issue by laowalter** [rainx/pytdx#185]
```
from pytdx.hq import TdxHq_API
api = TdxHq_API()
api.connect('119.147.212.81', 7709)
bars = api.get_security_bars(5,0, '399001', 0, 50) #周K线
```

bars[0] 数据正确
OrderedDict([('open', 11401.87),
             ('close', 11238.88),
             ('high', 11422.93),
             ('low', 11140.34),
             ('vol', 8995321.0),
             ('amount', 1252052697088.0),
             ('year', 2017),
             ('month', 10),
             ('day', 20),
             ('hour', 15),
             ('minute', 0),
             ('datetime', '2017-10-20 15:00')])

**bars[1] 数据错误** 时间和数据都不对

OrderedDict([('open', 11238.899),
             ('close', 11235.626),
             ('high', 11238.9),
             ('low', 11239.71),
             ('vol', 1.402150015920561e+49),
             ('amount', 6.421702055299326e+65),
             ('year', 37362),
             ('month', 45),
             ('day', 26),
             ('hour', 15),
             ('minute', 0),
             ('datetime', '**37362-45-26** 15:00')])

**Comment by heavendai** [comment]
在获取分钟数据时，遇到同样的问题。
data = self.hq_api.get_security_bars(8, market, code, 0, 10)
     name     open    close     high      low           vol        amount  year  month  day  hour  minute          datetime
0  395001  462.000  462.000  462.000  462.000  5.877472e-39  5.877472e-39  2019      3   18    14      51  2019-03-18 14:51
1  395001  462.062  462.005  462.002  462.065  5.877472e-39  5.877472e-39  2004      0    0     0       0  2004-00-00 00:00
2  395001  462.005  462.005  462.005  462.005  4.253530e+40  5.877472e-39  2004      0    0     0       0  2004-00-00 00:00
3  395001  462.005  462.005  462.005  462.005  5.877472e-39  4.287558e+40  2004      0    0     0       0  2004-00-00 00:00
4  395001  462.005  462.005  462.005  462.005  5.877472e-39  5.877472e-39  2004      0    0     0       0  2004-00-00 00:00
5  395001  462.005  462.005  462.005  462.005  5.877472e-39  5.877472e-39  2019      3   18    14      55  2019-03-18 14:55
6  395001  462.067  462.010  462.259  462.067  5.877472e-39  5.877472e-39  2004      0    0     0       0  2004-00-00 00:00
7  395001  462.010  462.010  462.010  462.072  6.533421e+40  5.877472e-39  2004      0    0     0       0  2004-00-00 00:00
8  395001  462.010  462.010  462.010  462.010  1.250000e-01  6.533421e+40  2004      0    0     0       0  2004-00-00 00:00
9  395001  462.010  462.010  462.010  462.010  5.877472e-39  1.250000e-01  2004      0    0     0       0  2004-00-00 00:00

**Comment by yutiansut** [comment]
这是指数 用 index的api
