### ISSUE TITLE
如何获取复权K线

### ISSUE THREAD

**Issue by hezhiyu1980** [rainx/pytdx#186]
在使用get_security_bars时只能获得不复权的K线，是否有方法获取复权后的数据？

**Comment by yutiansut** [comment]
这里实现了 https://github.com/QUANTAXIS/QUANTAXIS

**Comment by ylxseu** [comment]
> 这里实现了 https://github.com/QUANTAXIS/QUANTAXIS

使用QUANTAXIS获取前复权的日线时，提示CURRENTLY NOT SUPPORT REALTIME FUQUAN

请问如何获取非Realtime复权K线呢？
