### ISSUE TITLE
能否提供服务器测速并自动选择最快服务器的命令？

### ISSUE THREAD

**Issue by yinxiuqu** [rainx/pytdx#189]
我发现默认的服务器速度不是特别快，能否提供一个对服务器列表上的服务器地址测速并自动选择最优服务器的命令？

**Comment by yutiansut** [comment]
提供一个测速代码:  https://github.com/QUANTAXIS/QUANTAXIS/blob/master/QUANTAXIS/QAFetch/QATdx.py#L100
