### ISSUE TITLE
api.connect 返回值问题

### ISSUE THREAD

**Issue by liuyug** [rainx/pytdx#190]
api.connect('119.147.212.81', 7709) 连接 TDX 服务器，但只有失败和成功两个结果。

而 tdxhqapi.dll 返回更多信息，其中“ 最后交易日期” 很重要，因为 getSecurityQuotes 函数里，只有时间，没有日期，在休息日调用函数，需要日期

···
connect to 106.120.74.86:7709
[['服务器名称', '最后交易日期', '接口过期日期'], ['招商证券北京行情', '20181123', '20991230']]
···

**Comment by yutiansut** [comment]
抓的不是hqapi.dll的包
