### ISSUE TITLE
请问使用pytdx获取行情有没有次数限制啊？

### ISSUE THREAD

**Issue by fulai-dbs** [rainx/pytdx#194]
@rainx 致最可敬的版主啊，请问使用pytdx获取行情有没有次数限制啊？我想写一个基于pytdx 的自动分析系统，需要频繁通过pytdx获取行情数据，如果太过频繁会不会被系统封ip啊？烦请帮忙解答下，多谢。 @rainx

**Comment by yutiansut** [comment]
会的  能缓存到本地尽量缓存到本地

**Comment by fulai-dbs** [comment]
请问需要将访问速度和次数限制到多少以下啊？



--
Fulai

在 2019-01-25 15:55:30，"Vincent yu" <notifications@github.com> 写道：


会的 能缓存到本地尽量缓存到本地

**Comment by rainx** [comment]
每个行情服务器的配置和版本不同，所以可能结果都不太一样 @fulai-dbs
