### ISSUE TITLE
请问获取的行情里面是否有时间戳字段？

### ISSUE THREAD

**Issue by lin6peter** [rainx/pytdx#198]
get_security_quotes后获取的quotes里面有个reversed_bytes0，有点像时间戳，但好像又不太对，不知道怎么看，想问下行情里面有时间戳么？谢谢

**Comment by yutiansut** [comment]
没有

**Comment by yutiansut** [comment]
...按错了 那个reversedbyte0 没啥意义 确实像时间一样但是没啥用
