### ISSUE TITLE
上证综指的信息应该如何获得？(用get_security_bars获得数据是错误)

### ISSUE THREAD

**Issue by oda356** [rainx/pytdx#205]
请问上证综指的数据应该如何获得呢？

我使用self.tdxApi.get_security_bars(9,1, '000001', 0, days)去取得的上证指数数据是错误的，比如在2019/4/20日取得self.tdxApi.get_security_bars(9,1, '000001', 0, 5)的返回数据除了第一条是正确的4月15日数据，其余四条都是像如下datetime和其他数据不正确的数据：

`OrderedDict([('open', 3191.42), ('close', 3189.37), ('high', 3180.55), ('low', 3201.74), ('vol', 5.006487271204065e+55), ('amount', 325455441821696.0), ('year', 87377), ('month', 97), ('day', 14), ('hour', 15), ('minute', 0), ('datetime', '87377-97-14 15:00')])`

所以正确的取上证数据的方法应该是什么呢？或者上述问题是get_security_bars有解析错误导致的呢？谢谢~

**Comment by purocean** [comment]
试试这个 get_index_bars

**Comment by oda356** [comment]
> 试试这个 get_index_bars

谢谢，我去试试
