### ISSUE TITLE
请问，pytdx的工作原理是什么？

### ISSUE THREAD

**Issue by hwypengsir** [rainx/pytdx#208]
pytdx 的api可以获得各种数据,我翻看了整个源码，也不清楚其中的原理。
从网站上获得信息，发出http请求，为了获得公司f10  数据，
http://quotes.money.163.com/f10/gszl_600023.html
发出请求，地址如上，获得相应，解析这个网页就可以获得数据了。
pytdx呢？
api.get_company_info_category(TDXParams.MARKET_SZ, '600023')
它是通过什么协议和服务器交互的？

**Comment by yutiansut** [comment]
二进制协议的解析
