### ISSUE TITLE
why ResourceWarning happens?

### ISSUE THREAD

**Issue by hbaaron** [rainx/pytdx#209]
```
C:\apps\Miniconda3\envs\stock\lib\site-packages\pkg_resources\_vendor\pyparsing.py:1383: ResourceWarning: unclosed <pytdx.base_socket_client.TrafficStatSocket fd=5684, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 56908), raddr=('58.210.106.91', 7709)>
  loc,tokens = self.parseImpl( instring, preloc, doActions )
```

pytdx version: 1.6.8

`        try:
            if not con:
                con = TdxHq_API(heartbeat=True, raise_exception=False, auto_retry=True)
                con.connect(ip, port, time_out=3)

            t1 = time.time()
            res = None
            for i in range(3):
                res = con.get_security_count(0)
                if res is None:
                    break
            if res:
                rtt = (time.time() - t1) / 3
                if rtt <= threshold:
                    success = True
                    return con, rtt, name, ip, port
                else:
                    raise TimeoutError
        except (socket.timeout, TimeoutError):
            logger.warning(
                "failed to connect to server %s(%s:%s) due to exceed rtt threshold, expected %s, actual %s",
                name, ip, port, threshold, rtt)
        except Exception as e:
            logger.warning("failed to connect to server %s(%s:%s)", name, ip, port)
            logger.exception(e)
        finally:
            if not success:
                self.release_connection({
                    "name": name,
                    "con": con,
                    "ip": ip,
                    "port": port
                })`

from log I can see:
2019-05-15 18:41:24,578 I solodata.collector.tdxfetcher:release_connection:116 | release connection with 218.85.139.20:7709
and the warning:
C:\apps\Miniconda3\envs\stock\lib\site-packages\pkg_resources\_vendor\pyparsing.py:1383: ResourceWarning: unclosed <pytdx.base_socket_client.TrafficStatSocket fd=6152, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 56901), raddr=('218.85.139.20', 7709)>
  loc,tokens = self.parseImpl( instring, preloc, doActions )

ps.
I have implemented a connection pool using ThreadExecutor

**Comment by yutiansut** [comment]
heartbeat=False and try again

**Comment by hbaaron** [comment]
试过，但数据仍会异常。见我另一个issue: https://github.com/rainx/pytdx/issues/210#issue-447205253

谢谢关注@yutiansut
