### ISSUE TITLE
大佬rainx 有办法可以获取通达信的level2高级行情吗？

### ISSUE THREAD

**Issue by dofish** [rainx/pytdx#211]
大佬rainx 有办法可以获取通达信的level2高级行情吗？

买了通达信账号是不是，跟普通行情原理差不多，只是增加用户认证这块？

大佬能给点指示吗？

**Comment by rainx** [comment]
我没有level2的账号，所以不太了解这方面的情况..貌似level2这块包含一个加解密的部分，所以应该难度要大些
