### ISSUE TITLE
get_transaction_data出现 time_out没办法走完整个stock list

### ISSUE THREAD

**Issue by gooongooon** [rainx/pytdx#220]
求助大佬：

用get_transaction_data对每一只股提取一次当天的的成家数据，比如想走一遍全A股，但是常常走到一部股就开始出现time out断开了，小白求教大佬如何解决，感谢！

**Comment by yutiansut** [comment]
try/except 记录错误信息 做容错

**Comment by gooongooon** [comment]
只懂交易不懂代码的小白表示不懂。。。

**Comment by bopo** [comment]
服务器超时了，做个异常处理，如果超时，重试一下。
