### ISSUE TITLE
现在交易server已经不能用了，请问有替代方案么

### ISSUE THREAD

**Issue by hanwenzh** [rainx/pytdx#222]
现在tradeserver已经不能用了，请问有替代方案么

**Comment by hanwenzh** [comment]
我弄了一个可以用的，也是那信，只是只绑定我自己一个账号，不知道你有没有办法patch掉
 



------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年9月30日(星期一) 下午4:30
收件人: "rainx/pytdx"<pytdx@noreply.github.com>; 
抄送: "张汉文"<270010904@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [rainx/pytdx] 现在交易server已经不能用了，请问有替代方案么 (#222)




某信升级了 老版本trade.dll都失效了 自行考虑别的几种模式吧

**Comment by yutiansut** [comment]
tradex?

**Comment by hanwenzh** [comment]
不是，是新的阿信dll函数与之前一样，我发你，你看下能不能允许多账号登录，你有Q么？我直接给你
 



------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年9月30日(星期一) 下午4:33
收件人: "rainx/pytdx"<pytdx@noreply.github.com>; 
抄送: "张汉文"<270010904@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [rainx/pytdx] 现在交易server已经不能用了，请问有替代方案么 (#222)




tradex?

**Comment by hanwenzh** [comment]
提示账户已过期 trade




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月30日(星期一) 下午4:33
收件人:&nbsp;"rainx/pytdx"<pytdx@noreply.github.com&gt;;
抄送:&nbsp;"张汉文"<270010904@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rainx/pytdx] 现在交易server已经不能用了，请问有替代方案么 (#222)




tradex?

**Comment by hanwenzh** [comment]
现在提示这个





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月30日(星期一) 下午4:33
收件人:&nbsp;"rainx/pytdx"<pytdx@noreply.github.com&gt;;
抄送:&nbsp;"张汉文"<270010904@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rainx/pytdx] 现在交易server已经不能用了，请问有替代方案么 (#222)




tradex?

**Comment by yutiansut** [comment]
en  现在不要用这个tradeServer了 升级了  换别的吧

**Comment by wanjochan** [comment]
@yutiansut 有没有什么可以选择的交易服务器组件推荐？

**Comment by fish1512** [comment]
同问.

**Comment by yutiansut** [comment]
> 同问.

可以考虑用界面的方式 有开源项目 像 puppet

**Comment by fish1512** [comment]
puppet这种项目有很多,但是这种部署不是很方便,考虑到界面交易,不能够保证下单准确率.我现在用的是收费版的trade.dll,可以登录,但是免费版的如何升级或者破解需要研究.

**Comment by markqiu** [comment]
还有收费版trade.dll?

**Comment by yutiansut** [comment]
对 tradex这种 不过也在查了 不知道还能用多久

**Comment by markqiu** [comment]
@yutiansut 谢谢!
