### ISSUE TITLE
还有可能升级兼容某信升级吗？

### ISSUE THREAD

**Issue by Iuty** [rainx/pytdx#228]
如题，用惯了pytdx，很舒服，不想换了。

**Comment by yutiansut** [comment]
交易不会继续兼容 &nbsp;行情接口短期应该不会改变



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Iuty <notifications@github.com&gt;
发送时间: 2019年11月18日 20:09
收件人: rainx/pytdx <pytdx@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[rainx/pytdx] 还有可能升级兼容某信升级吗？ (#228)

**Comment by fish1512** [comment]
> 如题，用惯了pytdx，很舒服，不想换了。
我也是,正在研究如何升级.有兴趣的话加qq:276224035
