### ISSUE TITLE
总资产 的金额不对，怎么回事啊

### ISSUE THREAD

**Issue by hardy110** [rainx/pytdx#230]
>>> api.query_data(client_id, 0)
{'data': [{'保留信息': '', '冻结资金': '0.00', '可取资金': '3.00', '可用资金': '35056.34', '币种': '0', '总资产': '', '最新市值': '10621.00', '资金余额': '3.00'}], 'success': True}

**Comment by hardy110** [comment]
不是这个软件的问题

**Comment by yutiansut** [comment]
> 不是这个软件的问题

钱不是问题 问题是没钱`溜
