### ISSUE TITLE
get_security_list这个函数的pre_close有误

### ISSUE THREAD

**Issue by abc100m** [rainx/pytdx#239]
#52  这个已经关掉的issue

今天测试了一下get_security_list，pre_close有些股是对的/有些是错的，不知道能不能弄一个完全正确的出来？

![image](https://user-images.githubusercontent.com/4769764/71912228-12f0d680-31b0-11ea-82e0-8f5a4b76e935.png)

![image](https://user-images.githubusercontent.com/4769764/71912313-3ddb2a80-31b0-11ea-9479-079281dbd0ee.png)

看2345这个只股，收盘价是3.46，昨日是3.35。 而get_security_list取出来是5.506，怎么算也不对了。

**Comment by abc100m** [comment]
图貌似是被墙了~~
```shell
##get_security_list取出来的是5.65
997  002195      100              2    二三四五  5.506006e+03
```

而现在看002195这支股票，收盘价是3.46，昨日收盘价是3.35。数据相差太多了

**Comment by abc100m** [comment]
```shell
908  002105      100              2    信隆健康  6.980000e+00
909  002106      100              2    莱宝高科  5.360575e+02
```
这里002105是对的，002106的是完全错误的（不管除不除100，实际上是10.12，这里5.36相差太远了）。总结规律，如果指数的幂不是0，那么大概率上就是错的。

请大神解决一下哈

**Comment by abc100m** [comment]
@yutiansut    https://github.com/QUANTAXIS/QUANTAXIS/issues/258  这个issue列出的问题不是简单的除100就能正确，实际上完全对不上，不知道大神你是否有正确解决了？

**Comment by abc100m** [comment]
由于不懂分析协议，所以找了一个 datochan的DTGear，这个大神的代码也有同样的一段解析代码。

pytdx现在看的解析代码是 <6sH8s4sBI4s，DTGear的解析代码是<6sH8sLBf2H，这个pre_close在pytdx上是I然后又处理（get_volume这个函数逆向的可能有BUG）。

现在把pre_close当作浮点数据解析出来，经过核查，看到的股票是没有问题了。但不知道基金/债券啥的有没有问题，我暂时不研究，所以问题先留在这

**Comment by Invincibl-e** [comment]
> 由于不懂分析协议，所以找了一个 datochan的DTGear，这个大神的代码也有同样的一段解析代码。
> 
> pytdx现在看的解析代码是 <6sH8s4sBI4s，DTGear的解析代码是<6sH8sLBf2H，这个pre_close在pytdx上是I然后又处理（get_volume这个函数逆向的可能有BUG）。
> 
> 现在把pre_close当作浮点数据解析出来，经过核查，看到的股票是没有问题了。但不知道基金/债券啥的有没有问题，我暂时不研究，所以问题先留在这
@abc100m 
原作者可能已经放弃维护了，要不要 fork 一下我和你共同维护一个新的？

**Comment by abc100m** [comment]
> 原作者可能已经放弃维护了，要不要 fork 一下我和你共同维护一个新的？

那你会分析逆向协议吗? 目前的板块数据貌似有了变化, 有些板块代码如 BK0847
看这个图
https://z1.dfcfw.com/2020/1/10/20200110212331117626093.jpg

**Comment by Invincibl-e** [comment]
> > 原作者可能已经放弃维护了，要不要 fork 一下我和你共同维护一个新的？
> > @Invincibl-e
> > 那你会分析逆向协议吗? 目前的板块数据貌似有了变化, 有些板块代码如 BK0847
> > 看这个图
> > https://z1.dfcfw.com/2020/1/10/20200110212331117626093.jpg

会的，有 IM 的联系方式吗？

**Comment by abc100m** [comment]
> 
> 会的，有 IM 的联系方式吗？

搜我的ID,  加vx

**Comment by yutiansut** [comment]
最近没怎么看issue 收到 这两天更新一下

**Comment by abc100m** [comment]
改为浮点数解析,暂时没有发现问题,先关掉这个issue了
