### ISSUE TITLE
get_security_bars取出来的vol值差了1个

### ISSUE THREAD

**Issue by abc100m** [rainx/pytdx#240]
测试了, 对深圳的002中小版\300创业板 都是正确的, 但是

深圳的 000006   取出来的vol比实际值小1
上海的600000   取出来的vol比实际值小1

误差不是很大, 有没有大佬来修复一下?

**Comment by abc100m** [comment]
@yutiansut

**Comment by Federer1976** [comment]
是哪一个函数里面的数据？

**Comment by abc100m** [comment]
> 是哪一个函数里面的数据？

get_security_bars 这个函数

**Comment by abc100m** [comment]
猜测是那个get_volume函数的问题, 它在round时有误差, 现在我已经改成按浮点数据解析.

暂时不知道还有没有问题,先关了这个
