### ISSUE TITLE
官方文档代码某行缺失

### ISSUE THREAD

**Issue by Pidbid** [rainx/pytdx#248]
文档地址：https://rainx.gitbooks.io/pytdx/content/pytdx_pool.html
文档标题：行情连接池 API （实验阶段）
具体位置：“例子”标题下示例代码中第14行
缺失代码：`from pytdx.pool.hqpool import TdxHqPool_API`
代码描述：未引入便调用

**Comment by yutiansut** [comment]
https://github.com/rainx/pytdx/commit/236283776ae022efc9b588b94a896761dbff7d0c

fixed  感谢 @Pidbid
