### ISSUE TITLE
可以获取level2的逐笔成交明细吗？

### ISSUE THREAD

**Issue by zelong77** [rainx/pytdx#251]
用hqget试了下查询分笔成交，似乎是3秒撮合的数据？可以获取到逐笔成交明细吗？

**Comment by yutiansut** [comment]
> 用hqget试了下查询分笔成交，似乎是3秒撮合的数据？可以获取到逐笔成交明细吗？

逐笔是l2的数据 需要账户以及比较复杂的解密 暂不支持
