### ISSUE TITLE
盘口价格是不是颠倒了

### ISSUE THREAD

**Issue by cwing2019** [rainx/pytdx#254]
应该 卖1 价 >买1价
data =api.get_security_quotes([(0, '000001'), (1, '600300')])
[OrderedDict([('market', 0), ('code', '000001'), ('active1', 233), ('price', 14.
33), ('last_close', 14.52), ('open', 14.45), ('high', 14.46), ('low', 14.3), ('r
eversed_bytes0', 9411868), ('reversed_bytes1', -1433), ('vol', 163827), ('cur_vo
l', 120), ('amount', 235615472.0), ('s_vol', 73037), ('b_vol', 90790), ('reverse
d_bytes2', 0), ('reversed_bytes3', 333145), ('bid1', 14.32), ('ask1', 14.33), ('
bid_vol1', 254), ('ask_vol1', 122), ('bid2', 14.31), ('ask2', 14.34), ('bid_vol2
', 3244), ('ask_vol2', 147), ('bid3', 14.3), ('ask3', 14.35), ('bid_vol3', 8828)
, ('ask_vol3', 44), ('bid4', 14.29), ('ask4', 14.36), ('bid_vol4', 665), ('ask_v
ol4', 378), ('bid5', 14.28), ('ask5', 14.37), ('bid_vol5', 1798), ('ask_vol5', 6
1), ('reversed_bytes4', (461,)), ('reversed_bytes5', 1), ('reversed_bytes6', 2),
 ('reversed_bytes7', -78), ('reversed_bytes8', 44), ('reversed_bytes9', 65509),
('active2', 233)]), OrderedDict([('market', 1), ('code', '600300'), ('active1',
206), ('price', 3.19), ('last_close', 3.22), ('open', 3.23), ('high', 3.26), ('l
ow', 3.17), ('reversed_bytes0', 9413182), ('reversed_bytes1', -319), ('vol', 923
19), ('cur_vol', 17), ('amount', 29632672.0), ('s_vol', 52664), ('b_vol', 39655)
, ('reversed_bytes2', -1), ('reversed_bytes3', 23262), ('bid1', 3.19), ('ask1',
3.2), ('bid_vol1', 5134), ('ask_vol1', 1546), ('bid2', 3.18), ('ask2', 3.21), ('
bid_vol2', 4450), ('ask_vol2', 1926), ('bid3', 3.17), ('ask3', 3.22), ('bid_vol3
', 4260), ('ask_vol3', 1933), ('bid4', 3.16), ('ask4', 3.23), ('bid_vol4', 2469)
, ('ask_vol4', 3290), ('bid5', 3.15), ('ask5', 3.24), ('bid_vol5', 2687), ('ask_
vol5', 1069), ('reversed_bytes4', (845,)), ('reversed_bytes5', 0), ('reversed_by
tes6', 12), ('reversed_bytes7', 18), ('reversed_bytes8', -11), ('reversed_bytes9
', 65475), ('active2', 206)])]

**Comment by yutiansut** [comment]
bid => 买  ask => 卖
