### ISSUE TITLE
通达信行情地址:

### ISSUE THREAD

**Issue by yutiansut** [rainx/pytdx#3]
有基础的有L2的

[HQHOST]
HostNum=6
PrimaryHost=0
HostName01=长城国瑞行情DNS
IPAddress01=tdx.xmzq.com.cn
Port01=7709
HostName02=长城国瑞电信1
IPAddress02=218.85.139.19
Port02=7709
HostName03=长城国瑞电信2
IPAddress03=218.85.139.20
Port03=7709
HostName04=长城国瑞网通
IPAddress04=58.23.131.163
Port04=7709
HostName05=上证云成都电信一
IPAddress05=218.6.170.47
Port05=7709
HostName06=上证云北京联通一
IPAddress06=123.125.108.14
Port06=7709

[INFOHOST]
INFO=1
HostNum=6
PrimaryHost=0
HostName01=长城国瑞资讯DNS
IPAddress01=tdx.xmzq.com.cn
Port01=7711
HostName02=长城国瑞资讯1
IPAddress02=218.85.139.19
Port02=7711
HostName03=长城国瑞资讯2
IPAddress03=218.85.139.20
Port03=7711
HostName04=长城国瑞网通
IPAddress04=58.23.131.163
Port04=7711
HostName05=上证云成都电信一
IPAddress05=218.6.170.47
Port05=7711
HostName06=上证云北京联通一
IPAddress06=123.125.108.14
Port06=7711
HostName01=高级行情_深圳双线1
IPAddress01=112.74.31.192
Port01=443

HostName02=高级行情_武汉电信2
IPAddress02=119.97.185.16
Port02=7709
Areas02=1

HostName03=高级行情_北京双线2
IPAddress03=59.110.61.176
Port03=7709

[L2Host]
HostNum=21

HostName01=高级行情_上海双线1
IPAddress01=106.14.76.29
Port01=7709

HostName02=高级行情_上海双线2
IPAddress02=139.196.174.113
Port02=7709

HostName03=高级行情_上海双线3
IPAddress03=139.196.175.118
Port03=7709

HostName04=高级行情_上海电信1
IPAddress04=61.152.107.173
Port04=7707
Areas04=1

HostName05=高级行情_上海电信2
IPAddress05=61.152.168.232
Port05=7715
Areas05=1

HostName06=高级行情_深圳电信1
IPAddress06=113.105.73.81
Port06=7721
Areas06=1

HostName07=高级行情_深圳电信2
IPAddress07=183.3.223.36
Port07=7709
Areas07=1

HostName08=高级行情_深圳电信3
IPAddress08=119.147.86.172
Port08=443
Areas08=1

HostName09=高级行情_深圳双线1
IPAddress09=112.74.31.192
Port09=443

HostName10=高级行情_深圳双线2
IPAddress10=120.77.76.11
Port10=7709

HostName11=高级行情_深圳双线3
IPAddress11=120.77.76.34
Port11=7709

HostName12=高级行情_东莞电信1
IPAddress12=113.105.142.138
Port12=7709
Areas12=1

HostName13=高级行情_东莞电信2
IPAddress13=113.105.142.139
Port13=7709
Areas13=1

HostName14=高级行情_武汉电信1
IPAddress14=119.97.185.4
Port14=7709
Areas14=1

HostName15=高级行情_武汉电信2
IPAddress15=119.97.185.16
Port15=7709
Areas15=1

HostName16=高级行情_北京联通
IPAddress16=61.135.142.90
Port16=443
Areas16=2

HostName17=高级行情_北京双线1
IPAddress17=101.200.127.219
Port17=443

HostName18=高级行情_北京双线2
IPAddress18=59.110.61.176
Port18=7709

HostName19=高级行情_济南联通
IPAddress19=123.129.245.202
Port19=80
Areas19=2

HostName20=高级行情_深圳双线4
IPAddress20=119.23.145.96
Port20=7709

HostName21=高级行情_上海双线4
IPAddress21=106.14.38.17
Port21=7709

[DSHOST]
HostNum=2

HostName01=实时全球主站1
IPAddress01=119.97.185.11
Port01=443

HostName02=实时全球主站2
IPAddress02=116.228.6.74
Port02=443

**Comment by rainx** [comment]
好的，有时间我试一下

**Comment by yutiansut** [comment]
我正在试呢~ 应该还有几个ip

**Comment by yutiansut** [comment]
上海电信主站Z1=180.153.18.170:7709

上海电信主站Z2=180.153.18.171:7709

上海电信主站Z80=180.153.18.172:80

北京联通主站Z1=202.108.253.130:7709

北京联通主站Z2=202.108.253.131:7709

北京联通主站Z80=202.108.253.139:80

杭州电信主站J1=60.191.117.167:7709

杭州电信主站J2=115.238.56.198:7709

杭州电信主站J3=218.75.126.9:7709

杭州电信主站J4=115.238.90.165:7709

杭州联通主站J1=124.160.88.183:7709

杭州联通主站J2=60.12.136.250:7709

杭州华数主站J1=218.108.98.244:7709

杭州华数主站J2=218.108.47.69:7709

义乌移动主站J1=223.94.89.115:7709

青岛联通主站W1=218.57.11.101:7709

青岛电信主站W1=58.58.33.123:7709

深圳电信主站Z1=14.17.75.71:7709

云行情上海电信Z1=114.80.63.12:7709

云行情上海电信Z2=114.80.63.35:7709

上海电信主站Z3=180.153.39.51:7709

**Comment by rainx** [comment]
把主机加到 hosts.py 文件离了

https://github.com/rainx/pytdx/blob/master/pytdx/config/hosts.py

**Comment by githubcyc** [comment]
你好，能够拿到板块指数的K线数据吗？  tdx android app 还有很多特色数据，不知大佬有没有研究，我已把so文件反汇编，函数太多，看不过来。

**Comment by rainx** [comment]
@githubcyc 反汇编看起来难度还是很大的，我之前都是抓包分析的，行情的数据包没有加密，所以还比较容易，移动版本还没有研究过

**Comment by daniel51** [comment]
@rainx 高级行情数据，貌似不能连接啊
