### ISSUE TITLE
建议：get_xdxr_info.py增加datetime

### ISSUE THREAD

**Issue by leegb** [rainx/pytdx#48]
row = OrderedDict(
                [
                    ('year', year),
                    ('month', month),
                    ('day', day),
                    ('datetime',datetime(year,month,day，15)),
                    .....
                ]
方便直接用于计算换手率，而不用通过year,month,day再处理。我自己添加，但是每次更新库之后，得自己改。

**Comment by yutiansut** [comment]
https://github.com/yutiansut/QUANTAXIS/blob/master/QUANTAXIS/QAFetch/QATdx.py#L330

可以直接洗出来

**Comment by leegb** [comment]
@yutiansut 我知道，可以自己处理，但是强迫症患，一点计算资源也不愿浪费。

**Comment by yutiansut** [comment]
一样的  程序里面处理和你自己处理 都浪费资源

**Comment by yutiansut** [comment]
难道写在pytdx里面 你调用的时候就不占用你的cpu了?

**Comment by leegb** [comment]
@yutiansut 好吧，我一般都直接把在源码你把year,month,date三列都干掉了，批量处理，一旦把数据都不齐，三列数据可占用不小的内存。

**Comment by yutiansut** [comment]
我也觉得干掉比较好 可能是因为兼容性吧 毕竟删东西会导致别人的代码不兼容
