### ISSUE TITLE
可不可以拿到按某一字段排序的股票列表或这个股票行情

### ISSUE THREAD

**Issue by JaysonAlbert** [rainx/pytdx#49]
在通达信行情主页，可以通过点击涨幅，涨速，换手等字段来获取按照相应字段排序的股票行情列表，所以是否可以提供相应功能的api

**Comment by yutiansut** [comment]
估计是拿到数据以后在软件内部实时计算的 不是行情传输的

**Comment by JaysonAlbert** [comment]
@yutiansut 研究了下，应该是拿到数据之后内部计算的，没5秒钟拿一次行情，然后根据用户的选择进行计算排序，好像是没有办法改变更新行情的速度的。
