### ISSUE TITLE
部分券商目前的7709端口服务器

### ISSUE THREAD

**Issue by solensolen** [rainx/pytdx#51]
下面是部分券商目前的TDX普通行情服务器IP，端口都是7709。目前我的网络多数都能PING通，可以参考使用于测试。

> 安信 | 112.95.140.74
> 安信 | 112.95.140.92
> 安信 | 112.95.140.93
> 安信 | 114.80.149.19
> 安信 | 114.80.149.21
> 安信 | 114.80.149.22
> 安信 | 114.80.149.91
> 安信 | 114.80.149.92
> 安信 | 121.14.104.60
> 安信 | 121.14.104.66
> 安信 | 123.126.133.13
> 安信 | 123.126.133.14
> 安信 | 123.126.133.21
> 安信 | 211.139.150.61
> 安信 | 59.36.5.11
> 广发 | 119.29.19.242
> 广发 | 123.138.29.107
> 广发 | 123.138.29.108
> 广发 | 124.232.142.29
> 广发 | 183.57.72.11
> 广发 | 183.57.72.12
> 广发 | 183.57.72.13
> 广发 | 183.57.72.15
> 广发 | 183.57.72.21
> 广发 | 183.57.72.22
> 广发 | 183.57.72.23
> 广发 | 183.57.72.24
> 广发 | 183.60.224.177
> 广发 | 183.60.224.178
> 国泰君安 | 113.105.92.100
> 国泰君安 | 113.105.92.101
> 国泰君安 | 113.105.92.102
> 国泰君安 | 113.105.92.103
> 国泰君安 | 113.105.92.104
> 国泰君安 | 113.105.92.99
> 国泰君安 | 117.34.114.13
> 国泰君安 | 117.34.114.14
> 国泰君安 | 117.34.114.15
> 国泰君安 | 117.34.114.16
> 国泰君安 | 117.34.114.17
> 国泰君安 | 117.34.114.18
> 国泰君安 | 117.34.114.20
> 国泰君安 | 117.34.114.27
> 国泰君安 | 117.34.114.30
> 国泰君安 | 117.34.114.31
> 国信 | 182.131.3.252
> 国信 | 183.60.224.11
> 国信 | 58.210.106.91
> 国信 | 58.63.254.216
> 国信 | 58.63.254.219
> 国信 | 58.63.254.247
> 海通 | 123.125.108.90
> 海通 | 175.6.5.153
> 海通 | 182.118.47.151
> 海通 | 182.131.3.245
> 海通 | 202.100.166.27
> 海通 | 222.161.249.156
> 海通 | 42.123.69.62
> 海通 | 58.63.254.191
> 海通 | 58.63.254.217
> 华林 | 120.55.172.97
> 华林 | 139.217.20.27
> 华林 | 202.100.166.21
> 华林 | 202.96.138.90
> 华林 | 218.106.92.182
> 华林 | 218.106.92.183
> 华林 | 220.178.55.71
> 华林 | 220.178.55.86

**Comment by yutiansut** [comment]
这个不错  我之前也攒了一部分 可以合起来

**Comment by yutiansut** [comment]
有基础的有L2的

[HQHOST]
HostNum=6
PrimaryHost=0
HostName01=长城国瑞行情DNS
IPAddress01=tdx.xmzq.com.cn
Port01=7709
HostName02=长城国瑞电信1
IPAddress02=218.85.139.19
Port02=7709
HostName03=长城国瑞电信2
IPAddress03=218.85.139.20
Port03=7709
HostName04=长城国瑞网通
IPAddress04=58.23.131.163
Port04=7709
HostName05=上证云成都电信一
IPAddress05=218.6.170.47
Port05=7709
HostName06=上证云北京联通一
IPAddress06=123.125.108.14
Port06=7709

[INFOHOST]
INFO=1
HostNum=6
PrimaryHost=0
HostName01=长城国瑞资讯DNS
IPAddress01=tdx.xmzq.com.cn
Port01=7711
HostName02=长城国瑞资讯1
IPAddress02=218.85.139.19
Port02=7711
HostName03=长城国瑞资讯2
IPAddress03=218.85.139.20
Port03=7711
HostName04=长城国瑞网通
IPAddress04=58.23.131.163
Port04=7711
HostName05=上证云成都电信一
IPAddress05=218.6.170.47
Port05=7711
HostName06=上证云北京联通一
IPAddress06=123.125.108.14
Port06=7711
HostName01=高级行情_深圳双线1
IPAddress01=112.74.31.192
Port01=443

HostName02=高级行情_武汉电信2
IPAddress02=119.97.185.16
Port02=7709
Areas02=1

HostName03=高级行情_北京双线2
IPAddress03=59.110.61.176
Port03=7709

[L2Host]
HostNum=21

HostName01=高级行情_上海双线1
IPAddress01=106.14.76.29
Port01=7709

HostName02=高级行情_上海双线2
IPAddress02=139.196.174.113
Port02=7709

HostName03=高级行情_上海双线3
IPAddress03=139.196.175.118
Port03=7709

HostName04=高级行情_上海电信1
IPAddress04=61.152.107.173
Port04=7707
Areas04=1

HostName05=高级行情_上海电信2
IPAddress05=61.152.168.232
Port05=7715
Areas05=1

HostName06=高级行情_深圳电信1
IPAddress06=113.105.73.81
Port06=7721
Areas06=1

HostName07=高级行情_深圳电信2
IPAddress07=183.3.223.36
Port07=7709
Areas07=1

HostName08=高级行情_深圳电信3
IPAddress08=119.147.86.172
Port08=443
Areas08=1

HostName09=高级行情_深圳双线1
IPAddress09=112.74.31.192
Port09=443

HostName10=高级行情_深圳双线2
IPAddress10=120.77.76.11
Port10=7709

HostName11=高级行情_深圳双线3
IPAddress11=120.77.76.34
Port11=7709

HostName12=高级行情_东莞电信1
IPAddress12=113.105.142.138
Port12=7709
Areas12=1

HostName13=高级行情_东莞电信2
IPAddress13=113.105.142.139
Port13=7709
Areas13=1

HostName14=高级行情_武汉电信1
IPAddress14=119.97.185.4
Port14=7709
Areas14=1

HostName15=高级行情_武汉电信2
IPAddress15=119.97.185.16
Port15=7709
Areas15=1

HostName16=高级行情_北京联通
IPAddress16=61.135.142.90
Port16=443
Areas16=2

HostName17=高级行情_北京双线1
IPAddress17=101.200.127.219
Port17=443

HostName18=高级行情_北京双线2
IPAddress18=59.110.61.176
Port18=7709

HostName19=高级行情_济南联通
IPAddress19=123.129.245.202
Port19=80
Areas19=2

HostName20=高级行情_深圳双线4
IPAddress20=119.23.145.96
Port20=7709

HostName21=高级行情_上海双线4
IPAddress21=106.14.38.17
Port21=7709

[DSHOST]
HostNum=2

HostName01=实时全球主站1
IPAddress01=119.97.185.11
Port01=443

HostName02=实时全球主站2
IPAddress02=116.228.6.74
Port02=443

**Comment by rainx** [comment]
cool

**Comment by rainx** [comment]
@solensolen 已经更新到 https://github.com/rainx/pytdx/blob/master/pytdx/config/hosts.py 感谢

**Comment by hadrianl** [comment]
L2目前能请求得到吗

**Comment by rainx** [comment]
@hadrianl 目前不支持l2
