### ISSUE TITLE
get_security_list与GitBook文档不一致，且pre_close有误

### ISSUE THREAD

**Issue by fanazhe** [rainx/pytdx#52]
如题

- GitBook中提到获取股票列表还有第3个参数“数量”，但实际代码（get_security_list.py）中并没有这个部分

- pre_close数值有很大比例有误，例如000001的20170909~20170911的pre_close (即20170908的close) 应为11.44，但目前API返回888.0024995803833

**Comment by rainx** [comment]
收到，文档我已经更新了，确实没有这个参数 

pre_close的问题我看一下
