### ISSUE TITLE
请教是否打算提供下单接口？

### ISSUE THREAD

**Issue by niucool** [rainx/pytdx#54]
感谢楼主分享，非常有用的代码，请问是否打算提供下单接口？如果可以的话那就太有用了。

**Comment by rainx** [comment]
可以用trade.dll ,我这里搞了一个封装,封装成rest server了，可以配合pytdx下单，具体看pytdx/trade部分
rest server在这里

https://github.com/rainx/TdxTradeServer

用QT开发的，估计自己编译会有点难度..

**Comment by niucool** [comment]
哦，我也注意到了，请问你用的trade.dll是理想论坛里面那个河蟹版吗？

**Comment by rainx** [comment]
应该是的，我是从其它地方找到的，不过我估计都一样

**Comment by zfsamzfsam** [comment]
交易API的通用化,最好是能兼容...

			RestFul-API,最好能兼容实盘易(ShiPanE)的
				http://www.iguuu.com/e
		
			Python-交易接口API,可以参考:
                                        实盘易(ShiPanE)
					futuquant API
					https://github.com/FutunnOpen/futuquant

**Comment by rainx** [comment]
@zfsamzfsam 我看一下

**Comment by niucool** [comment]
@rainx 用第三方闭源的程序问题就是怕有信息泄露问题，请教你怎么知道是否可靠呢？

**Comment by rainx** [comment]
@niucool 这个只能靠运气了，如果有时间可以反向工程一下trade.dll ,把里面所有的可能有网络传输的地方分析一下就可以了，或者用wireshark之类的抓包看看，不过这个比较花时间了，

**Comment by niucool** [comment]
@rainx  谢谢回复，我原来担心有这样的问题，就搞了个模拟键盘操作的程序，类似实盘易，自己用是够了。

**Comment by fanazhe** [comment]
@rainx @niucool 请问能否告知哪个trade.dll目前是可用的？谢谢！

**Comment by yutiansut** [comment]
08年的那个理想论坛 @fanazhe

**Comment by fanazhe** [comment]
@yutiansut 谢谢！

**Comment by rainx** [comment]
@fanazhe 直接用get_tts命令吧.
