### ISSUE TITLE
作者是直接解析的行情dll的那几个函数么

### ISSUE THREAD

**Issue by qiji12** [rainx/pytdx#56]
作者是直接解析的行情dll的那几个函数么，我通过wireshark抓包发现通达信PC端的连接流程要多了好多个信令，而pytdx只用了0c0218930001030003000d0001  0c0218940001030003000d0002 0c031899000120002000db0fd5d0c9ccd6a4a8af0000008fc22540130000d500c9ccbdf0d7ea00000002三个初始化语句，是咋发现只要这三个就可以了。

**Comment by yutiansut** [comment]
武林派不传之秘 @rainx   哈哈哈

**Comment by rainx** [comment]
@qiji12 是用wireshark抓取tradex 的请求..
