### ISSUE TITLE
和zipline整合的问题？

### ISSUE THREAD

**Issue by niucool** [rainx/pytdx#57]
刚才忽然想到如果下载的数据能存成zipline支持的格式，就能做成一个完整的回测系统，如果加上交易模块，自动交易就可以完美实现了，这就是中文版的zipline-live啊。请问有没有此计划？

**Comment by rainx** [comment]
关于通达信数据转换成zipline格式，我们目前已经实现了日线数据的转换，不过目前只在回测中使用，还没有接入实盘交易，由于是公司的项目，所以可能暂时还不太方便开源，而且的确目前的实现不是特别好，后面也不排除实现的好一些之后会把代码开放出来
