### ISSUE TITLE
我已经有个通达信的L2账户，我怎么通过这个程序来读取L2数据呢

### ISSUE THREAD

**Issue by haohello** [rainx/pytdx#60]

**Comment by haohello** [comment]
比如说每天的逐笔成交数据

**Comment by rainx** [comment]
暂时还不支持l2数据的读取

**Comment by rainx** [comment]
逐笔的话，普通行情里面好像也有对应的接口

**Comment by yutiansut** [comment]
是的  逐笔成交有 逐笔委托没有  本来想在框架内做一个订单簿分析的  结果没找到逐笔委托

**Comment by haohello** [comment]
怎么可以取到通达信那种的逐笔成交数据呢

**Comment by yutiansut** [comment]
history_transaction

**Comment by niucool** [comment]
@haohello 请问是否L2有抓包的pcap数据？我有兴趣分析看看

**Comment by haohello** [comment]
@niucool 我没有的啊， 这个怎么搞啊？ 我是菜鸟。

**Comment by niucool** [comment]
@haohello 用wireshark抓包会吗？

**Comment by haohello** [comment]
@niucool 没用过，我学一下啊。

**Comment by haohello** [comment]
@niucool L2的数据你那边有进展吗？ 我看已经有人可以实现了啊。

**Comment by yutiansut** [comment]
tradex一直是可以拿L2的

**Comment by pkunico** [comment]
tradex 怎么拿L2的十档行情呢？
