### ISSUE TITLE
关于美股复权的问题

### ISSUE THREAD

**Issue by niucool** [rainx/pytdx#61]
最近使用pytdx下美股数据，确实很爽。有个问题请教下：
现在下载美股的股票数据是未复权数据吗？如果是的话，如何进行复权啊？这个对回测影响非常大啊。
另外关于美股数据的准确性，请问是否有过研究？
谢谢

**Comment by niucool** [comment]
刚才测试了一下，通达信美股intraday延时有15分钟，对于实时交易来说，基本等于没用。请问谁知道怎么获取level2行情呢？

**Comment by yutiansut** [comment]
15分钟？！

**Comment by niucool** [comment]
是的，15分钟。明天再试一次看看。

**Comment by niucool** [comment]
今天又测试了一次，延时问题的确存在，大部分时候是15分钟。

**Comment by yutiansut** [comment]
给一下你测试的具体代码吧

**Comment by niucool** [comment]
比如调用 api.get_instrument_quote(74, "XIV")
和 api.get_instrument_bars(TDXParams.KLINE_TYPE_1MIN, 74, 'XIV', 0, 10)
再和当前时间对比以下就可以知道

**Comment by shenxingbei** [comment]
据我所知，很多软件和网站提供的美股行情都是15分钟延迟行情。想要获得实时行情，需要付费购买，或者选用支持实时行情的数据源。通达信，同花顺这类不提供美股交易功能的行情软件，看来也是用的延时行情。

**Comment by yutiansut** [comment]
给你点个赞 by the way 通达信的扩展行情是第三方提供的 不是通达信自己提供的

**Comment by niucool** [comment]
是的，开启客户端的时候有提示，15分钟的延时是没法用于实时交易的，只能下载历史数据用于回测。不过历史数据里面也有诸多问题，比如数据不全等，而且用来做美股回测的人少，所以这个数据源是不太可靠的。

**Comment by yutiansut** [comment]
美股的话....zipline应该不错
