### ISSUE TITLE
获取的F10信息，有的分页获取不到，不同服务器获取的F10子项内容也不相同，这个是正常的吧？

### ISSUE THREAD

**Issue by tlhbjfunny** [rainx/pytdx#63]
get_company_info_category、get_company_info_content，这两个函数从不同的服务器获取到的F10内容不同，这个是正常的吧？另外为什么有的F10内的分页获取的是空呢？不是固定的，如一个股的”分红扩股“是空，另一个股可能是 ”行业分析“获取空。

**Comment by yutiansut** [comment]
是的

**Comment by tlhbjfunny** [comment]
刚看到tushare要发布新接口了，看来是rainx写的核心啊，恭喜两大高人联手，不过担心这个接口数据访问量上去了话，会不会被tdx封啊？

**Comment by yutiansut** [comment]
直接拷贝源代码还在上面修修改改 我没看出来这哪里是联手
