### ISSUE TITLE
# 授权协议

### ISSUE THREAD

**Issue by yutiansut** [rainx/pytdx#64]
建议MIT或者GPL

**Comment by yutiansut** [comment]
@rainx

**Comment by rainx** [comment]
@yutiansut 收到，我从珠海回去研究一下..

**Comment by yutiansut** [comment]
@rainx  不知道你知不知道...tushare全盘复制了pytdx的代码 还修改了部分源代码

**Comment by rainx** [comment]
@yutiansut jimmy在放假之前和我提过它可能回使用部分功能，具体使用那些我还没有了解，节后可能回和他见一下

**Comment by yutiansut** [comment]
他直接把pytdx文件夹复制到他项目里面了

**Comment by rwayan** [comment]
兄弟在珠海啊，好近。

**Comment by rainx** [comment]
仔细考虑了一下，因为我的说明中提到这个代码只做个人研究和习作，不作为商业用途，为了避免通达信的纠纷，就先不加license了
