### ISSUE TITLE
get_volume 函数好像误差较大

### ISSUE THREAD

**Issue by user20171001** [rainx/pytdx#65]
GetFinanceInfo里面日期类型的ipo_date对不上

**Comment by yutiansut** [comment]
恩?  截个图?或者代码

**Comment by rainx** [comment]
@user20171001 最好能提供一个参数列表和对应的正确数值，这样查找起来比较方便，对于get_volume,的确有可能有偏差...

**Comment by rainx** [comment]
线关闭了，估计出了GetFinacneInfo，其它用到get_volumne的地方也有类似的问题，后面遇到的时候单处理了
