### ISSUE TITLE
get_transaction_data 获取实时完整交易数据的问题

### ISSUE THREAD

**Issue by cybercall** [rainx/pytdx#67]
`get_transaction_data(market, code, start, count)`

当 start是0,表示的是从最新交易数据列表里,返回 count 个交易数据
但当运行过程中发生了交易或运行的耗时比较长时,通过上面的接口,是无如实现分批获取完整的交易数据的.
比如
`
data1 = get_transaction_data(market, code, 0, 100)
data2 = get_transaction_data(market, code, 100, 100)
data3 = get_transaction_data(market, code, 0, 200)
`
data3  是有可能不等于 (data1 + data2)
因为在获取data2时,交易系统可能已经发生了交易,这时的 start =100 的交易已经不再是 获取data1时那的start = 100 那把交易了.

如果是这样,不知道要怎么才能完整获取实时的全部交易数据.

**Comment by user20171001** [comment]
有时间来过滤吗?

**Comment by yutiansut** [comment]
什么?

**Comment by cybercall** [comment]
>.....看完全部的api 你就知道有个叫 history_transaction_data的接口

但我需要的是 实时,不是历史啊...

**Comment by rainx** [comment]
这个只能手动去重复过滤了.. @cybercall
