### ISSUE TITLE
获取历史分笔数据不全

### ISSUE THREAD

**Issue by billwei19** [rainx/pytdx#7]
get_history_transaction_data（）只能获取最多2000行分笔数据，9:30后的数据基本没有办法获取到。

**Comment by rainx** [comment]
是的，这个是通达信的历史行情数据的限制，如果要获取更多的数据，可以通过行情软件导出历史行情文件，然后再进行解析

**Comment by billwei19** [comment]
请问您知道现在哪个行情软件可以批量导出历史分笔数据吗？我手上的通达信软件全部只能导出历史一分钟数据。

**Comment by zfsamzfsam** [comment]
对于API获取数据的限制,能否定义常量固定下来?

**Comment by rainx** [comment]
@billwei19 哦，我可能之前理解成k线数据了，分笔数据我记得通达信的网站上好像有一份

**Comment by rainx** [comment]
@zfsamzfsam 嗯，后面争取加上这部分

**Comment by rainx** [comment]
@zfsamzfsam 增加了一些常量 https://github.com/rainx/pytdx/blob/master/pytdx/params.py

**Comment by yutiansut** [comment]
,,,,,

**Comment by yutiansut** [comment]
@rainx 你你你你

**Comment by yutiansut** [comment]
@rainx  @billwei19 @zfsamzfsam 
并不是不全的,是你要不断的改开始的数据指针位置:
![文档参考](https://rainx.gitbooks.io/pytdx/content/pytdx_hq.html)
```python
api.get_history_transaction_data(TDXParams.MARKET_SZ, '000001', 0, 10, 20170209)
```
这里面第三个参数,是起始的指针位置:

所以完整的示例是这样的
```python
 from pytdx.hq import TdxHq_API
 api=TdxHq_API()
 with api.connect():
       data=api.get_history_transaction_data(TDXParams.MARKET_SZ, '000001', 2001, 2000, 20170209)+api.get_history_transaction_data(TDXParams.MARKET_SZ, '000001', 0, 2000, 20170209)


print(api.to_df(data))
```

**Comment by billwei19** [comment]
@yutiansut @rainx 经试验，确实如 @yutiansut 所提示的，如每页获取最多的2000条，要翻到下一页数据就要从2000开始. 也就是说，需要自己去判断是否已到页尾/首页。 谢谢 @yutiansut 给的提示，帮了大忙。

**Comment by yutiansut** [comment]
@billwei19 @rainx 一般来说 6000条肯定足够了  要是不放心 可以再加一个判断 比如 拿到数据以后判断是不是9:30了  如果是的话就return结果 如果不是 继续叠加

**Comment by billwei19** [comment]
@yutiansut 但问题是，接口貌似每页数据最多只能获取2000条数据每页。如何能一次获取6000条呢？

**Comment by yutiansut** [comment]
@billwei19 你在外面包一层函数啊....包到6000

**Comment by billwei19** [comment]
我现在就是用的while来循环获取。我以为你还有什么方法可以更简单一行搞定。不过，真的很感谢，棒了大忙.

**Comment by yutiansut** [comment]
#21 恩恩 可以看看这个
