### ISSUE TITLE
 这段时间在休假中(9-23 to 10-5)... 

### ISSUE THREAD

**Issue by rainx** [rainx/pytdx#70]
带娃休假中，这段时间一支没有接触电脑，今天在朋友的电脑上看到好多issue,等我回家后回慢慢处理，大概10月5号之后应该就可以了...

**Comment by user20171001** [comment]
堵在路上的时候，正好可以研究下，哈哈

**Comment by rainx** [comment]
呵呵，休假结束了，close this
