### ISSUE TITLE
api.get_security_bars 接口读取通达信板块指数880只能只能读取一天数据

### ISSUE THREAD

**Issue by windskysolo** [rainx/pytdx#71]
df = pd.DataFrame(api.get_security_bars(9,1, '880870', 0, 1))
df
     open   close    high     low      vol        amount  year  month  day  \
0  848.78  855.89  855.89  848.75  66504.0  1.417299e+10  2017      9   29   

   hour  minute          datetime  
0    15       0  2017-09-29 15:00  

两天有问题
df = pd.DataFrame(api.get_security_bars(9,1, '880870', 0, 2))
df
       open    close      high       low           vol        amount  year  \
0   854.270   846.99   855.750   846.990  6.105400e+04  1.355574e+10  2017   
1  1269.439  1269.44  1271.229  1276.549  2.047139e+42  1.282384e+63   747   

   month  day  hour  minute          datetime  
0      9   28    15       0  2017-09-28 15:00  
1     11   32    15       0   747-11-32 15:00

**Comment by yutiansut** [comment]
已经解决过这个问题了 还是仔细看文档吧

**Comment by windskysolo** [comment]
多谢，用指数接口就可以了
pd.DataFrame(api.get_index_bars(9, 1, '880870', 0, 800))
        open    close     high      low       vol        amount  year  month  \
0    1001.07   996.66  1007.05   996.54  115117.0  2.990586e+10  2016     10   
1     993.90  1000.08  1000.60   987.99   94245.0  2.655179e+10  2016     10   
2     999.96  1014.37  1014.95   999.61  124615.0  3.676003e+10  2016     11   
3    1011.84  1009.47  1018.65  1008.64  129202.0  3.758704e+10  2016     11   
4    1006.03  1018.50  1026.78  1005.45  168434.0  4.526283e+10  2016     11   
5    1017.94  1019.83  1025.36  1016.57  136101.0  3.838956e+10  2016     11   
6    1019.88  1019.91  1023.43  1015.65  114382.0  3.237059e+10  2016     11   
7    1023.76  1024.99  1026.80  1019.65  126936.0  3.494841e+10  2016     11   
8    1024.19  1014.62  1025.48  1002.81  147504.0  4.047015e+10  2016     11   
9    1023.19  1031.11  1032.95  1023.02  154997.0  4.240000e+10  2016     11   
10   1031.01  1041.46  1041.46  1029.71  187021.0  4.730246e+10  2016     11   
11   1038.98  1045.40  1052.53  1038.74  176119.0  4.555385e+10  2016     11   
12   1044.48  1047.93  1047.96  1038.57  135861.0  3.666704e+10  2016     11   
13   1049.05  1048.30  1051.67  1046.94  148872.0  4.064055e+10  2016     11   
14   1044.68  1042.28  1045.04  1034.43  141198.0  3.319693e+10  2016     11   
15   1040.59  1039.14  1046.48  1037.78  138874.0  3.618277e+10  2016     11   
16   1036.80  1046.07  1046.14  1036.73  145506.0  4.052132e+10  2016     11   
17   1046.58  1058.02  1058.06  1046.58  170214.0  4.543648e+10  2016     11   
18   1057.73  1048.24  1059.26  1045.61  149878.0  4.166324e+10  2016     11   
19   1046.33  1043.45  1054.50  1040.40  140730.0  3.782939e+10  2016     11   
20   1041.48  1045.23  1045.31  1022.90  131335.0  3.522188e+10  2016     11   
21   1048.14  1044.70  1049.69  1041.35  131644.0  3.411068e+10  2016     11   
22   1040.60  1037.75  1045.24  1037.47  156512.0  3.690214e+10  2016     11   
23   1034.52  1040.82  1046.96  1033.79  131295.0  3.101128e+10  2016     11   
24   1040.34  1045.80  1047.46  1040.34  121631.0  2.910199e+10  2016     12   
25   1045.30  1021.58  1045.31  1020.75  128698.0  3.168947e+10  2016     12   
26   1011.23  1015.65  1023.94  1009.90   95559.0  2.244285e+10  2016     12   
27   1017.28  1015.74  1021.04  1014.89   80337.0  2.016816e+10  2016     12   
28   1016.57  1023.08  1023.19  1013.05   80685.0  2.107554e+10  2016     12   
29   1024.09  1012.41  1024.09  1011.41   89223.0  2.349689e+10  2016     12   
..       ...      ...      ...      ...       ...           ...   ...    ...   
200   814.58   820.91   821.07   814.58   55094.0  1.029815e+10  2017      8   
201   819.69   820.08   825.45   818.70   48410.0  9.881407e+09  2017      8   
202   818.43   815.81   819.69   812.49   39762.0  7.986651e+09  2017      8   
203   816.06   811.65   817.82   811.19   38231.0  8.123684e+09  2017      8   
204   810.08   821.53   822.11   810.08   45122.0  9.327612e+09  2017      8   
205   822.88   840.58   844.37   822.88  100914.0  1.764361e+10  2017      8   
206   842.42   841.42   845.64   840.09   83048.0  1.561042e+10  2017      8   
207   840.73   841.54   844.54   839.66   65584.0  1.265370e+10  2017      8   
208   840.87   850.02   850.03   840.87   58823.0  1.206244e+10  2017      8   
209   850.81   851.84   853.09   847.99   64164.0  1.385658e+10  2017      9   
210   851.37   853.28   854.31   848.82   68394.0  1.476292e+10  2017      9   
211   852.68   856.97   858.89   852.57   66657.0  1.422091e+10  2017      9   
212   856.62   861.22   861.56   852.59   75164.0  1.609440e+10  2017      9   
213   861.92   866.83   874.65   861.92   94841.0  2.245059e+10  2017      9   
214   865.18   867.59   869.38   862.92   72408.0  1.694252e+10  2017      9   
215   867.13   874.45   874.58   867.01   70786.0  1.607938e+10  2017      9   
216   875.28   868.35   875.77   866.95   90226.0  1.957145e+10  2017      9   
217   866.69   871.80   871.80   863.94   59904.0  1.378506e+10  2017      9   
218   872.25   873.10   877.97   870.26   70901.0  1.617868e+10  2017      9   
219   870.83   870.26   874.86   868.39   82855.0  1.676656e+10  2017      9   
220   869.92   883.36   883.36   869.82   96413.0  1.843672e+10  2017      9   
221   882.84   881.13   885.19   878.20   88252.0  1.828784e+10  2017      9   
222   879.60   887.69   887.76   879.14   86744.0  1.836766e+10  2017      9   
223   887.23   881.39   891.64   881.21   84555.0  1.837167e+10  2017      9   
224   878.35   875.40   879.10   872.36   70526.0  1.564623e+10  2017      9   
225   872.11   854.49   872.83   853.96   76673.0  1.593463e+10  2017      9   
226   852.25   849.72   855.36   845.37   65590.0  1.374371e+10  2017      9   
227   850.38   855.22   856.45   849.80   55874.0  1.248387e+10  2017      9   
228   854.27   846.99   855.75   846.99   61054.0  1.355574e+10  2017      9   
229   848.78   855.89   855.89   848.75   66504.0  1.417299e+10  2017      9   

     day  hour  minute          datetime  up_count  down_count  
0     28    15       0  2016-10-28 15:00        54         151  
1     31    15       0  2016-10-31 15:00       116          84  
2      1    15       0  2016-11-01 15:00       193          15  
3      2    15       0  2016-11-02 15:00        60         147  
4      3    15       0  2016-11-03 15:00       137          67  
5      4    15       0  2016-11-04 15:00       118          92  
6      7    15       0  2016-11-07 15:00        88         117  
7      8    15       0  2016-11-08 15:00       133          69  
8      9    15       0  2016-11-09 15:00        37         171  
9     10    15       0  2016-11-10 15:00       203           4  
10    11    15       0  2016-11-11 15:00       108          99  
11    14    15       0  2016-11-14 15:00       133          69  
12    15    15       0  2016-11-15 15:00       118          81  
13    16    15       0  2016-11-16 15:00        82         118  
14    17    15       0  2016-11-17 15:00        48         150  
15    18    15       0  2016-11-18 15:00       100          97  
16    21    15       0  2016-11-21 15:00       151          44  
17    22    15       0  2016-11-22 15:00       138          58  
18    23    15       0  2016-11-23 15:00        31         168  
19    24    15       0  2016-11-24 15:00        50         144  
20    25    15       0  2016-11-25 15:00        93         103  
21    28    15       0  2016-11-28 15:00        59         139  
22    29    15       0  2016-11-29 15:00        34         166  
23    30    15       0  2016-11-30 15:00       116          82  
24     1    15       0  2016-12-01 15:00       113          84  
25     2    15       0  2016-12-02 15:00        16         183  
26     5    15       0  2016-12-05 15:00       102          92  
27     6    15       0  2016-12-06 15:00       125          71  
28     7    15       0  2016-12-07 15:00       162          34  
29     8    15       0  2016-12-08 15:00        32         170  
..   ...   ...     ...               ...       ...         ...  
200   21    15       0  2017-08-21 15:00        94          19  
201   22    15       0  2017-08-22 15:00        32          80  
202   23    15       0  2017-08-23 15:00        44          69  
203   24    15       0  2017-08-24 15:00        26          89  
204   25    15       0  2017-08-25 15:00       105          11  
205   28    15       0  2017-08-28 15:00       112           3  
206   29    15       0  2017-08-29 15:00        65          49  
207   30    15       0  2017-08-30 15:00        25          93  
208   31    15       0  2017-08-31 15:00       107          13  
209    1    15       0  2017-09-01 15:00        58          65  
210    4    15       0  2017-09-04 15:00        63          57  
211    5    15       0  2017-09-05 15:00        61          62  
212    6    15       0  2017-09-06 15:00        69          57  
213    7    15       0  2017-09-07 15:00        83          44  
214    8    15       0  2017-09-08 15:00        53          71  
215   11    15       0  2017-09-11 15:00        93          32  
216   12    15       0  2017-09-12 15:00        20         110  
217   13    15       0  2017-09-13 15:00        84          44  
218   14    15       0  2017-09-14 15:00        45          89  
219   15    15       0  2017-09-15 15:00        41          90  
220   18    15       0  2017-09-18 15:00       104          30  
221   19    15       0  2017-09-19 15:00        57          75  
222   20    15       0  2017-09-20 15:00       102          34  
223   21    15       0  2017-09-21 15:00        37          97  
224   22    15       0  2017-09-22 15:00        47          90  
225   25    15       0  2017-09-25 15:00        29         110  
226   26    15       0  2017-09-26 15:00        40         100  
227   27    15       0  2017-09-27 15:00       103          37  
228   28    15       0  2017-09-28 15:00        28         114  
229   29    15       0  2017-09-29 15:00       115          30  

[230 rows x 14 columns]

**Comment by yutiansut** [comment]
..... 你还是不仔细看文档啊......

**Comment by yutiansut** [comment]
https://rainx.gitbooks.io/pytdx/content/batch_download_data.html
