### ISSUE TITLE
get_finance_info总现金流好像不对(几个值在负数，不存在时都解析错误了)

### ISSUE THREAD

**Issue by user20171001** [rainx/pytdx#73]
0,’000166‘
from pprint import pprint as p
p(dict(api.get_finance_info(0, "000166")))

'zongxianjinliu': 4.885450038502473e+83,

实际值是 -421915.69

**Comment by yutiansut** [comment]
总现金金流是负数?

**Comment by rainx** [comment]
对接口做了修改,并且发布到fix_get_finance_info_values_error分支上，请帮忙验证，如果没有问题，我就merge并发布了..  @user20171001  https://github.com/rainx/pytdx/tree/fix_get_finance_info_values_error

In [4]: api.get_finance_info(0, "000166")
Out[4]: 
OrderedDict([('market', 0),
             ('code', '000166'),
             ('liutongguben', 1228204170),
             ('province', 2),
             ('industry', 1),
             ('updated_date', 3.3021034989831656e-38),
             ('ipo_date', 20150126),
             ('zongguben', 1240782053),
             ('guojiagu', 1211226688),
             ('faqirenfarengu', 1241541827),
             ('farengu', 6090260.5),
             ('bgu', 0.0),
             ('hgu', 0.0),
             ('zhigonggu', 0.0),
             ('zongzichan', 282965728.0),
             ('liudongzichan', 0.0),
             ('gudingzichan', 1291541.125),
             ('wuxingzichan', 108713.296875),
             ('gudongrenshu', 319402.0),
             ('liudongfuzhai', 0.0),
             ('changqifuzhai', 1783494.25),
             ('zibengongjijin', 4444946.0),
             ('jingzichan', 52560152.0),
             ('zhuyingshouru', 6062480.5),
             ('zhuyinglirun', 0.0),
             ('yingshouzhangkuan', 0.0),
             ('yingyelirun', 2740739.5),
             ('touzishouyu', 1518048.75),
             ('jingyingxianjinliu', -17081922.0),
             ('zongxianjinliu', -4219157.0),
             ('cunhuo', 0.0),
             ('lirunzonghe', 2739530.25),
             ('shuihoulirun', 2105136.25),
             ('jinglirun', 2049964.875),
             ('weifenlirun', 16683958.0),
             ('baoliu1', 0.0),
             ('baoliu2', 6.0)])

**Comment by yutiansut** [comment]
@rainx 赞 你这个接口正好是我为数不多的没有用的一个api 哈哈哈

**Comment by user20171001** [comment]
赞, 用粉笔画线很简单,难的是找到在哪里画
修改是从原来的整数解码加自定义装换改到浮点数解码了
当初看到那个转换函数是觉得有点别扭,不符合pythonic,新的修改不用那个转换函数了
这下很pythonic,应该是没问题的了

**Comment by rainx** [comment]
ok.. 估计其它用到get_volume的地方都有可能有类似的问题，后续我慢慢修复吧..

**Comment by rainx** [comment]
已经升级到 1.45了..
