### ISSUE TITLE
是不是不支持Python 3.6啊？

### ISSUE THREAD

**Issue by haohello** [rainx/pytdx#74]
运行以下代码得到错误： ModuleNotFoundError: No module named 'pytdx.hq'; 'pytdx' is not a package

`from pytdx.hq import TdxHq_API`

`api = TdxHq_API()`

`if api.connect('119.147.212.81', 7709):`
    `data = api.to_df(api.get_security_bars(9, 0, '000001', 0, 10))  # 返回DataFrame`
    `print(data)`
    `api.disconnect()`

**Comment by yutiansut** [comment]
支持的 你没安装好而已

**Comment by rainx** [comment]
支持3.6 https://travis-ci.org/rainx/pytdx

**Comment by haohello** [comment]
@yutiansut 我是菜鸟啊， 完全按照示例pip install这么安装的啊

**Comment by haohello** [comment]
这么安装的， `pip install pytdx`

**Comment by leaout** [comment]
能说一下怎么解决的吗

> 运行以下代码得到错误： ModuleNotFoundError: No module named 'pytdx.hq'; 'pytdx' is not a package
> 
> `from pytdx.hq import TdxHq_API`
> 
> `api = TdxHq_API()`
> 
> `if api.connect('119.147.212.81', 7709):`
> `data = api.to_df(api.get_security_bars(9, 0, '000001', 0, 10)) # 返回DataFrame`
> `print(data)`
> `api.disconnect()`
