### ISSUE TITLE
接口好像读不到期货商品的数据

### ISSUE THREAD

**Issue by lizhi2013** [rainx/pytdx#75]
#FG1801
....
data=api.get_instrument_bars(0, 1, "FG1801", 0, 100)    
...
我是这么读的，而且我查询商品信息 也没有比如1801的商品
aa=api.get_instrument_info(1, 1000)
是数据源的问题吗

**Comment by lizhi2013** [comment]
搞定了 是市场写错了改成如下即可
data=api.get_instrument_bars(0, 28, "FG1801", 0, 100)

**Comment by yutiansut** [comment]
close issue吧
