### ISSUE TITLE
怎么在读取K线数据的时候同时得到当时的量比和换手率的数据呢？

### ISSUE THREAD

**Issue by haohello** [rainx/pytdx#76]
比如1分钟K线或者5分钟K线，返回每笔数据的时候同时也返回当时的量比和换手率, 求解啊！

**Comment by yutiansut** [comment]
量比自己算的

**Comment by rainx** [comment]
恩，目前只返回通达信服务器中直接返回的数据

**Comment by yutiansut** [comment]
@rainx  我建议搞一套High_Level_api和Low_level_api的概念 区分开来

**Comment by rainx** [comment]
@yutiansut 的确是这样比较好一点，不过我感觉High Level的API可以考虑做成独立的数据包，兼容多个数据源，不过不知道这样是不是好抽象，类似你在quanaxis里面的结构就很好，不过现在免费的数据源却是是有点少了..
