### ISSUE TITLE
get_security_quotes每次只能拿到80只股票的行情吗

### ISSUE THREAD

**Issue by JaysonAlbert** [rainx/pytdx#77]
如果每次只能拿80只的行情，4000+支全市场行情每次要拿50+次才可以哦

**Comment by yutiansut** [comment]
是800只...

**Comment by yutiansut** [comment]
是的  参见这个实现https://github.com/yutiansut/QUANTAXIS/blob/master/QUANTAXIS/QAFetch/QATdx.py#L291

**Comment by yutiansut** [comment]
```python

def QA_fetch_get_stock_realtime(code=['000001', '000002'], ip=best_ip, port=7709):
    api = TdxHq_API()
    __data = pd.DataFrame()
    with api.connect(ip, port):
        code = [code] if type(code) is str else code
        for id_ in range(int(len(code) / 80) + 1):
            __data = __data.append(api.to_df(api.get_security_quotes(
                [(__select_market_code(x), x) for x in code[80 * id_:80 * (id_ + 1)]])))
            __data['datetime'] = datetime.datetime.now()
        data = __data[['datetime', 'code', 'open', 'high', 'low', 'price']]
        return data.set_index('code', drop=False, inplace=False)

```

**Comment by JaysonAlbert** [comment]
@yutiansut 我就是参考你这个写的，但是也是在for循环里面请求了50多次啊

**Comment by yutiansut** [comment]
@JaysonAlbert 是的 不过这个应该可以考虑用asyncio来优化改进一下

**Comment by JaysonAlbert** [comment]
我再研究研究

**Comment by rainx** [comment]
@JaysonAlbert 我这边测试一般每次取200个

**Comment by JaysonAlbert** [comment]
@rainx 但是我发现股票列表长度超过80的话，返回的dataframe的shape都是80*44的

**Comment by rainx** [comment]
@JaysonAlbert 哦，我算错了，应该都是80

**Comment by yutiansut** [comment]
恩恩 这块异步应该不错

**Comment by jeffery82** [comment]
@yutiansut 如果用asyncio并发查询全市场股票的话，服务器会不会把IP封了？

**Comment by yutiansut** [comment]
@jeffery82  我测了下 很容易返回None 不提供代码了 自己写的话 尽量少点

**Comment by yutiansut** [comment]
@jeffery82 也可能是我并发太多了 建议少点吧

**Comment by zrd0001** [comment]
大家好:
我在测试api.get_security_quotes()这个方法时发现了如下的问题 希望能帮忙解决一下.
问题   (1,'688123')  为一个已经停牌的股票.  一次读取多个股票的数据(比如80个一组),由于没有 方法 删除已停牌的股票代码,就使得这一组读取的数据都被置为 None.   
有问题的语句如下:
  sjjtt = api.get_security_quotes((0, '000001')) # 正常返回数据
  sjjtt = api.get_security_quotes((1,'688123'))  # 返回 None
  sjjtt = api.get_security_quotes([(0,'000001'),(1,'688123')]) #返回的也是None
由于不知怎么发新帖子所以就将问题在方法名相同的问题贴中提出了望谅解.
