### ISSUE TITLE
 CustomerBlockReader() 是不是有个地方没有去掉“\x00” 

### ISSUE THREAD

**Issue by laowalter** [rainx/pytdx#81]
我的系统是：通达信金融终端7.35
```
from pytdx.reader.block_reader import CustomerBlockReader
df = CustomerBlockReader().get_df('/mnt/cifs/new_tdx/T0002/blocknew')

df.blockname.tolist()[:4]

['即时选股', '条件选股\x00愣', '条件选股\x00愣', '条件选股\x00愣']
```

**Comment by JaysonAlbert** [comment]
![image](https://user-images.githubusercontent.com/6207775/31593583-1f1b3c2c-b262-11e7-88c3-1f717a2d3457.png)
@laowalter 你改一下这两个地方试试，因为我是按照广发证券客户端测试的，板块名称和板块简写分别是50字节，和70字节长度，不知道其它客户端怎么样。

**Comment by JaysonAlbert** [comment]
@laowalter 第二个改动的地方是一个bug，我已经提交了pull request，还没有给合并

**Comment by yutiansut** [comment]
@rainx

**Comment by laowalter** [comment]
@JaysonAlbert  ['自选股2', '即时选股', '条件选股', 'A']， 输出正确了。

**Comment by JaysonAlbert** [comment]
@laowalter ok，那这个issue可以关掉了吧

**Comment by rainx** [comment]
更新到 1.50
