### ISSUE TITLE
如果是通达信付费用户, 如何发送用户名和密码?

### ISSUE THREAD

**Issue by exbidata** [rainx/pytdx#90]
当前登录只发送 ip & port, 如何发送用户名和密码?
def connect(self, ip='101.227.73.20', port=7709):

**Comment by rainx** [comment]
暂时不支持付费用户部分的功能

**Comment by exbidata** [comment]
我想帮忙编写付费用户部分, 你有什么提示吗？ 应该从哪儿开始?

**Comment by rainx** [comment]
可以加我的微信 rainx1982 , 付费用户部分如果是加密传输的，不建议公开代码，还是有一定的风险的
