### ISSUE TITLE
哪个函数可以得到完整历史分钟k线 ?

### ISSUE THREAD

**Issue by exbidata** [rainx/pytdx#95]
get_history_minute_time_data 只有 price/volume, 没有 Open/High/Low
哪个函数可以得到完整历史分钟k线 (Open/High/Low/Close/Volume/Count) ?

**Comment by rainx** [comment]
只有 get_security_bars 获取k线，但是获取数量有限， 全部历史可以获取历史分笔或者分时成交自己合成
